### ISSUE TITLE
Investigate restrictions for service names

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1134]
At the moment the character set `(a-z A-Z 0-9 _ -)` is allowed for `service.name`. 
This is a rather restrictive validation. Investigate if this can be extended.

**Comment by simitt** [comment]
Update:
Tried indexing and showing additional characters in the APM UI and dashboards and found following:

* restricted in APM UI: `.%/\#?`
* allowed: `|!@$ˆ&*()_=+-;:'\"|><'`, cyrrilic, 

(More research needed)

**Comment by watson** [comment]
The Node.js agent just landed a PR that now automatically picks up the service name from the application so that the user doesn't have to specify it any more. But this increases the risk of users getting a service name with invalid characters.

Last time we discussed this we felt that it would be nice if we could allow as many different unicode characters as possible. The outcome of the discussion was:

> Biggest issue might be if we decide to use the service name as part of the index name. We will look more into loosen the limitations in the issue above and implement it after we knowing the approach.

It would be nice if we can set aside time to get to the bottom of this soon - preferably before 6.5 😅

**Comment by jalvz** [comment]
6.5 was a long time ago... are we good closing this, or is still a hot topic?
