### ISSUE TITLE
docs: add keystore command docs

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#11637]
The [`apm-server keystore`](https://www.elastic.co/guide/en/apm/server/7.15/keystore.html) docs got dropped somewhere along the way - they don't appear to exist for 8.x. We should bring them back for the APM Server Binary docs.

**Comment by bmorelli25** [comment]
The keystore docs were purposefully removed in https://github.com/elastic/apm-server/pull/10791.

The removal was based on a comment in [this doc ](https://docs.google.com/document/d/1x_eKhOgOZwD4AzPOcTK2BIfpSR85rYupYmGRofmpwOs/edit#heading=h.vtmv3n3bx4in)(sorry, internal link).

That being said, it'd be super easy to add these docs back in if you think we should. I'll assign @colleenmcginnis to this issue and move it to our next sprint. We'll plan on re-adding the docs unless we hear otherwise from you or @simitt.

**Comment by axw** [comment]
@simitt can you please comment if you think we should leave them undocumented? If we do then I guess we're effectively deprecating those commands, and should think about what the alternative(s) are, e.g. Kubernetes secrets.

**Comment by simitt** [comment]
I'm fine with documenting the keystore commands until we have a better solution.
