### ISSUE TITLE
Allow overriding of meta data in intake V2

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-server#1175]
In Java, you can have multiple applications in one JVM and multiple frameworks in one application. Therefore, I propose that the intake API should allow that specific payload attributes of service can be overridden. Related Java agent issue: https://github.com/elastic/apm-agent-java/issues/136

The [payload](https://github.com/elastic/apm-server/blob/master/docs/spec/transactions/payload.json) JSON schema defines meta-data which is valid for all the transactions and spans it contains. Instead of allowing only some attributes like `service.name` to be overridden in a `Transaction`, add the [`service`](https://github.com/elastic/apm-server/blob/master/docs/spec/service.json) object to `Transaction`, `Span` and `Error`. This allows default values to be set in the `Payload` "header" but allows specific objects to override the defaults. In languages where there can only ever be one `service.name`, this requires no changes and no additional overhead.

One problem with that approach is that there are required attributes in [`service`](https://github.com/elastic/apm-server/blob/master/docs/spec/service.json) like `agent` and `name`. These should not have to be repeated. If possible with JSON schema, it would be nice to remove the `required` part from the service definition and only add it where necessary whenever the `service` is used.

**Comment by axw** [comment]
I was looking into https://github.com/elastic/apm-agent-go/issues/69 today, seeing what needed to be changed in the server. Turns out it already works, probably by accident :)

The server merges `metadata.service` with `{transaction,span,error}.context.service`, with fields in the former (service-level) overriding the latter (transaction-level):

https://github.com/elastic/apm-server/blob/37091eadc2d914ab8a195f922a3d6e4c8ab911b8/model/metadata/metadata.go#L94-L103

This is backwards for what @felixbarny is requesting, but works in my case where I just want to set the framework at the transaction level. I think we'll want to swap the merge order.

**Comment by simitt** [comment]
related Issue https://github.com/elastic/apm-server/issues/1255

**Comment by simitt** [comment]
@elastic/apm-agent-devs could you please define which fields you'd like to send on an event level. 

We need to agree on whether the information per event should be _merged with_ the object sent in the metadata or should be _set instead_ of the metadata information. 

At the moment the `user` can be set per event. In case a user is given in the metadata and per event, the information from the event is stored, and the information from the metadata is ignored for this user.

**Comment by felixbarny** [comment]
I'd like to send `service` fields on an event level. I'd prefer to only set values which differ from the meta data. I guess that means to merge.

**Comment by gregkalapos** [comment]
> I'd like to send `service` fields on an event level. 

+1 from .NET on `service`.

**Comment by simitt** [comment]
If we _merge_ the data, it means you need to ensure to send all attributes you want to be overwritten in the event. E.g. if the user sent within metadata is a different one than the one sent in the event (for whichever reason this should ever happen), you would need to send all user data in the event, as otherwise two unrelated user objects would be mixed. Same for every other object you want to overwrite. 
To me this looks more error prone than setting either the event object or the metadata object. I do see your point sending as little information as possible though, so both options are fine with me. I just wanted to point out the potential risk.

**Comment by jalvz** [comment]
fwiw, the least complicated to address this imo is:

- define all attributes in the events (service, system, etc) - this way event types are fully defined in isolation.
- treat `metadata` as a bag of defaults of field and/or objects (ie if any field is not set in the event, grab it from the metadata)
- ideally, `metadata` would explicitly define which types are the defaults for, eg. a list of objects like `{field: context.user, value: {id:123, email:whatev}, types: [error, transaction]}` but probably we can't change this on time for 7.0 any ways.

**Comment by felixbarny** [comment]
What would be a use case to set the user in the meta data?

The use cases I have in mind are overriding the service name and the framework name on a per-event basis. I don't think these would be breaking changes.

If there is a use case to set data which is usually associated with transactions or spans, like user, in the meta data, I feel like we should discuss that separately.

**Comment by simitt** [comment]
> What would be a use case to set the user in the meta data?

The API already allows sending a user in the metadata since 6.5. I assume sending user data via metadata makes especially sense for the rum agent, for sending information about the currently logged in user.

**Comment by simitt** [comment]
I suggest we implement the same solution for whichever data are given in the metadata and can be overriden per event, so there is a clear definition of the outcome of _overriding_ data.

**Comment by axw** [comment]
> @elastic/apm-agent-devs could you please define which fields you'd like to send on an event level.

I currently only need to set `service.framework`.

**Comment by simitt** [comment]
I am going to add `service.framework` to `context` on a per event type as a bugfix, since this is working in 6.x. 
@gregkalapos and @felixbarny are there other parts from `service` that make sense for your agents to send up on a per event basis? 
For now I'd like to avoid just adding all metadata or service fields without a real use case. As soon as the code is there we need to maintain it and overriding fields is error prone as we saw in the past.

**Comment by felixbarny** [comment]
`service.name` as well. It would be great if `service.name` could be made optional in the meta data in case it's set per event. See also the first post of this thread.

**Comment by gregkalapos** [comment]
> `service.name` as well. It would be great if `service.name` could be made optional in the meta data in case it's set per event. See also the first post of this thread.

Same from me. I think service.name is more important... the framework will be probably the same, but with different service names - at least in .NET that would be very typical.

**Comment by simitt** [comment]
@felixbarny I can see why making `service.name` and `service.agent` optional here makes sense
I am going to drop all requirements for which fields need to be set on the `context.service`.

**Comment by felixbarny** [comment]
But it probably still makes sense to check if the resulting document has `service.name` set. I don't think there is a need to make `service.agent` overridable or optional though.

**Comment by simitt** [comment]
Giving it a second thought I am not going to only define _some_ service attributes to be overridable, as this would for probably lead to more discussion and confusion in the future.

**Comment by felixbarny** [comment]
Gotcha, I'm fine with that
