### ISSUE TITLE
OTLP HTTP 404 - /v1/traces

### ISSUE THREAD

**Issue by NicklasWallgren** [elastic/apm-server#12353]
We're not able to access the OTEL HTTP paths using APM Server version 7.17.5. The Elastic APM/HTTP paths works fine (/intake/v2/). We have also tried with the OTEL gRPC paths (opentelemetry.proto.collector.trace.v1.TraceService/Export) with the same outcome.

What can be the issue?

Received response
```json
{
  "error": "404 page not found"
}
```

**Comment by simitt** [comment]
Sending OTLP over HTTP is only supported from version `8.3` onwards ([8.3 changelog](https://www.elastic.co/guide/en/apm/guide/current/release-notes-8.3.html#_added_9)). 

For future questions and unconfirmed bugs, please open an issue in the [discuss forum](https://discuss.elastic.co/c/observability/apm/58) instead of here.
