### ISSUE TITLE
Handling errors in Intake V2

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1240]
Figure out behaviour if an error happens while processing requests for Intake v2:

* how to handle synchronous errors (validation, decoding)
* how to handle async errors (transformation, writing to output, ..)

Are there cases where the connection should be closed or an immediate error should be returned or should there only be a summary returned?

Implementation depends on elastic/apm-server#1238

**Comment by roncohen** [comment]
In the implementation here https://github.com/elastic/apm-server/issues/1238 I've effectively categorized errors into two separate categories:

* errors that cause the server to immediately respond and close the connection
  * content type error
  * metadata errors
  * errors reading from the ndjson stream
* errors that allow apm server to continue processing. The errors become part of the summary response in the end.
  * json decoding issues
  * schema validation issues
  * full queue

At the moment, the "timeout waiting to be processed" error has not been adapted to the v2 response format. I'll change that so that the format is v2 compatible when appropriate and it will be in the "immediate response" category. 

async error handling (transform, writing to output..) haven't changed

**Comment by simitt** [comment]
@roncohen you are working/have been working on this right? Could you move it to progress or done please and assign to you?

**Comment by roncohen** [comment]
I'll close this for now as the implementation is working: https://github.com/elastic/apm-server/issues/1298#issuecomment-417624871
