### ISSUE TITLE
Detect and notify to UI publishing failures

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#1269]
If APM server can’t write to ES, it will eventually reject and log request, but we should notify somehow to the UI that there is a problem.

Ideally we can pinpoint the root cause: eg low disk watermark, connection timeout, fields explosion, etc.

**Comment by graphaelli** [comment]
Two related ideas, both around identifying when intervention is likely required to address the situation

1. Add metric for output rate limiting - I think elasticsearch is the only one we support that will do this, by returning 429s.  A libbeat update is likely the best route to implement this.

2. Add metrics for output publish latency.  This addresses the issue with requiring the output to explicitly push back - this is, backpressure can be applied by slowing down responses to the producer - this is how the logstash protocol does it.  A distribution of latencies seems most useful here.  THe metric should be stateless, rather than resetting every polling period, as there are many pollers of this information.

**Comment by jalvz** [comment]
I think adding metrics for publish latency is a good idea, maybe we can track that somewhere else... do we still have some monitoring task open?

**Comment by axw** [comment]
When running under Fleet, logs and metrics will be available in Kibana by default.

Additional metrics around output response time may be useful. I think these belong in libbeat.

Closing this as I don't think there's anything to do in the near future for apm-server. Please open new, more specific, issues if you still see a need.
