### ISSUE TITLE
monitoring: apm-server only ships a subset of monitoring metrics

### ISSUE THREAD

**Issue by carsonip** [elastic/apm-server#13475]
Discovered by #13244 

EA managed apm-server is only shipping a subset of apm-server monitoring metrics. This limits observability of EA managed apm-server. The problem is spread over the following use cases:

- APM server self-monitoring
  - metricsets `state`, `stats`
  - indices (not data stream) `.monitoring-beats-7-*`
  - does NOT use TSDS, but fields are unmapped due to dynamic: false
  - code in ES repo [monitoring-beats.json](https://github.com/elastic/elasticsearch/blob/27b177938f9e78fa341a523bc8ff333e04939222/x-pack/plugin/core/template-resources/src/main/resources/monitoring-beats.json)
- Stack monitoring: metricbeat beat-xpack module uses index template embedded in ES
  - metricsets `state`, `stats`
  - data stream `.monitoring-beats-8-mb`
  - use case: Elastic Cloud self-monitoring, metricbeat standalone beat-xpack
  - does NOT use TSDS, but fields are unmapped due to dynamic: false
  - code in ES repo [monitoring-beats-mb.json](https://github.com/elastic/elasticsearch/blob/27b177938f9e78fa341a523bc8ff333e04939222/x-pack/plugin/core/template-resources/src/main/resources/monitoring-beats-mb.json)
- Metricbeat without xpack: metricbeat beat module
  - metricsets `state`, `stats`
  - data stream `metricbeat-*`
  - use case: metricbeat standalone
  - does NOT use TSDS, fields are mapped dynamically
  - [code in beats repo](https://github.com/elastic/beats/blob/b226be23223f92e517196c752ff40cc4c4ea2e3c/metricbeat/module/beat/_meta/fields.yml)
- EA integration
  - metricsets `stats` only
  - data stream `metrics-elastic_agent.apm_server.*` (see [code](https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/application/monitoring/v1_monitor.go#L665))
  - use case: elastic-agent standalone with monitoring
  - to see EA integration package content: `POST kbn:/api/fleet/epm/packages/elastic_agent`
  - uses TSDS, see https://github.com/elastic/integrations/pull/7214 . The issue with using TSDS is that unmapped fields are dropped, as it uses synthetic source.
  - [code in integrations repo](https://github.com/elastic/integrations/tree/main/packages/elastic_agent/data_stream/apm_server_metrics)
  - it doesn't contain any apm-server fields as of today

Unknowns:
- As the outdated mappings above contain fields that are no longer used, mapping generated from `apm-server:5066/stats` will not be pure addition. Not sure if dropping a field mapping will be problematic.
  - Should it be a superset of all historically available monitoring fields? That doesn't sound realistic either

**Comment by carsonip** [comment]
# Testing

Completed testing on all https://github.com/elastic/beats/pull/40127, https://github.com/elastic/elasticsearch/pull/110568, and https://github.com/elastic/integrations/pull/10414. Note that both https://github.com/elastic/elasticsearch/pull/110568 and https://github.com/elastic/integrations/pull/10414 require https://github.com/elastic/beats/pull/40127 to have `output.elasticsearch.*` metrics parsed.

## apm-server self monitoring (indices `.monitoring-beats-7-*`)
### before
![image](https://github.com/elastic/apm-server/assets/9133397/fc4d5881-0a21-411a-bbe6-1c84f694ff30)
### after
![image](https://github.com/elastic/apm-server/assets/9133397/ac411167-c527-4a53-a577-12ce266199e5)

## metricbeat beat-xpack (DS `.monitoring-beats-8-mb`)
### before
![image](https://github.com/elastic/apm-server/assets/9133397/bb1cb99c-0c08-4fe5-9060-52f00b30555a)
### after
![image](https://github.com/elastic/apm-server/assets/9133397/6daf10a1-d7ba-4a4c-8c44-92d1118a91db)

## metricbeat beat standalone (DS `metricbeat-*`)
### before
![image](https://github.com/elastic/apm-server/assets/9133397/25cfc312-d033-4a35-83e5-e1bafc5d8e7e)
### after
![image](https://github.com/elastic/apm-server/assets/9133397/2b13a29a-1934-4097-924f-582dba807fc7)

## EA agent monitoring (DS `metrics-elastic_agent-apm_server-*`)
### before
![image](https://github.com/elastic/apm-server/assets/9133397/f5a88a0d-9b86-4b79-9abf-352da31f8c2a)
### after
![image](https://github.com/elastic/apm-server/assets/9133397/c06ff440-c7b7-4346-ad70-f0fe62d4ba50)

# Long term solution

While the Python script in https://github.com/elastic/apm-server/pull/13638 generates the correct mapping for all the above use cases, this approach is not very maintainable. Ideally, having `dynamic: true` like metricbeat standalone enables apm-server monitoring fields to be mapped dynamically and will require minimal maintenance. However, since EA agent mapping already has TSDB enabled, disabling TSDB now and enabling dynamic mapping sounds like a step back.

**Comment by lahsivjar** [comment]
Tested on 8.15 BC2:

- [ ] APM server self-monitoring: tested with ESS elasticsearch, the [backport PR](https://github.com/elastic/elasticsearch/pull/110687) was not merged. It is merged now, and will require testing again in BC3.
- [ ] APM server stack monitoring: tested on ESS, the [backport PR](https://github.com/elastic/elasticsearch/pull/110687) was not merged. It is merged now, and will require testing again in BC3.
- [x] Metricbeat without x-pack, tested locally with apm-server [008b12a7e9929ce00e01040e67e83cf19c0b7de7](https://github.com/elastic/apm-server/commits/008b12a7e9929ce00e01040e67e83cf19c0b7de7) and beats [417ac43a6193bdf26da490d41532b2f2d5bc3f70](https://github.com/elastic/beats/commits/417ac43a6193bdf26da490d41532b2f2d5bc3f70)
  <details>

  <summary> Snapshots from testing </summary>

  <img width="889" alt="Screenshot 2024-07-18 at 3 54 14 PM" src="https://github.com/user-attachments/assets/080869bd-6b03-4d46-8467-31cd12476171">
  <img width="776" alt="Screenshot 2024-07-18 at 3 54 32 PM" src="https://github.com/user-attachments/assets/1f53d0e4-1108-4093-8695-b3959ef1fc9b">

  </details>
- [x] EA integration tested with locally running EA using elastic-agent-package [475d247d16a94af14b75d991a8da3d63d68e8042](https://github.com/elastic/elastic-agent-package/commits/475d247d16a94af14b75d991a8da3d63d68e8042). ❌ While the test succeeded, I had to manually upgrade EA integration as the version bundled in Kibana is still older (`v1.20.0`) whereas the latest version is `v2.0.1` - since this is not related to the current issue, marking this point as done.
  <details>

  <summary> Snapshots from testing </summary>

<img width="1019" alt="Screenshot 2024-07-18 at 4 56 56 PM" src="https://github.com/user-attachments/assets/c824d98c-b54a-40b9-8c2e-cdb534c54602">
<img width="858" alt="Screenshot 2024-07-18 at 4 57 08 PM" src="https://github.com/user-attachments/assets/f228c59d-362a-44d2-a145-13dc7dac48f7">

  </details>

**Comment by carsonip** [comment]
Moved all remaining tasks to #13731 . Closing this issue as the bug of missing metrics is now fixed.
