### ISSUE TITLE
Benchmark how APM Server scales vertically

### ISSUE THREAD

**Issue by alvarolobato** [elastic/apm-server#1414]
We need to measure how APM server scales when we increase the size of the machine

**Comment by simitt** [comment]
Load tests have been performed on cloud instances of different sizes. The load generation tool [hey-apm](https://github.com/elastic/hey-apm/commit/3d1ac086339476570b2a069fdc4f5ee21bc68a7b) was deployed to separate cloud instances, every [APM Server](https://github.com/elastic/apm-server/commit/b629cc6721b300c2e7a671cfbf598e15b12bddbe) was set up on a separate instance. All APM Servers were using the new Intake V2 API and shared the same ES cloud instance. To avoid skewing results by sharing the ES instance, tests were not run in parallel. 

**Performed load tests:**
For the streaming load tests a http connection is kept open for 10s, and then it awaits the server response. While being open, the throttling parameter sets how many payloads are sent over the request per second. For the non streaming tests a new http request is created for every payload. The throttle parameter limits the number of requests per second. The number of concurrent agents simulates different agents sending their payloads over separate requests. 
* Payload 1 error with 500 frames, with different settings for concurrent agents (1, 5, 10) and throttling (30,50,100).
* Payload 1 transaction with 5 spans and 500 frames each for concurrent agents (1, 5) and throttling 100
* Payload 20 transaction with 5 spans and 5 frames each for concurrent agents (1, 5) and throttling 100

**Outcome and limitations:**
* The throughput and behaviour of the APM Server instances differs a lot depending on how the sent events look like (large amount of stacktrace frames, multiple flushes with only a few events, e.g. realistic scenario for sending unhandled exceptions, ..).
* APM Server behaves slightly better when the V2 Intake protocol is used in the _streaming_ way, rather than in the _non-streaming_ way. 
* Processing stacktrace frames is CPU heavy server side. In case events have a large amount of frames (tested with up to 500 frames), a CPU optimized server setup is recommended and vertical scaling has the most effect. Events with many frames are considered to rather be an edge case. 
* In v2 the `concurrent_request` setting was removed. It cannot be guaranteed to not overwhelm the server with too many events being sent, as the decoding and validation happens before the events are enqueued into the memory queue and a potential `queue is full` error occurs. Suggestion: Introduce a new setting `concurrent_events` for v2, aligned with the size of the memory queue to throttle the processing of events, to avoid overwhelming the server. 
* Smallest tested machine `~512mb, 1 core` is easily memory and CPU bound, and can be overwhelmed easily. Settings for the internal memory queue need to be rather conservative (tested with `32`), leading to a restricted throughput. Upgrading to a machine with `~4GB, 1 core` showed quite good performance improvements, for events with a large amount of stacktrace frames, but also for events with almost no frames. 
* Upgrading from a `~4 GB, 1 core` to a `~8 GB, 2 core` or a `15 GB, 4 core` machine improved throughput for events with a larger amount of frames, as increase of number of CPUs could be leveraged. It also has the advantage of being able to keep a larger internal memory queue as buffer, in case of temporary unavailability of ES. However, in most test cases with small amount of stacktrace frames the throughput could not have been increased significantly, especially as the CPU limits could not be reached but the throughput was still throttled. 
Investigations why the throughput does not scale accordingly to scaling up the APM Server hosts indicate a lock contention issue when looking at APM Server traces. The httpprof traces show that the Server spends a lot of idle time, spent to a large percentage in the publisher code (queue, enqueue to publish, etc.). 

APM Server (start with default options):
Blocking:
![screen shot 2018-11-12 at 10 38 15](https://user-images.githubusercontent.com/5555349/48339542-bd32a400-e668-11e8-818d-83a44081b429.png)

Trace for APM Server with ES output and default settings:
![screen shot 2018-11-12 at 10 57 53](https://user-images.githubusercontent.com/5555349/48340035-d851e380-e669-11e8-85f7-547a8d2175f9.png)

As a baseline we compare to an APM Server setup where publishing events is disabled by using `-N`. This means all the processing in the APM code base is still happening, but the libbeat output is ignored:
![screen shot 2018-11-12 at 10 54 49](https://user-images.githubusercontent.com/5555349/48339994-bfe1c900-e669-11e8-8815-bfb09d757f10.png)

Investigations with different settings for memory flushing intervals and queue sizes did show slight modifications of the traces, but no significant improvements. This leads to the assumption that the Server throughput is limited due to internal publishing handling.

**Comment by alvarolobato** [comment]
Thanks @simitt awesome writeup.

**Comment by simitt** [comment]
**Update**:
We found 2 reasons for throttled throughput:
* ES instances were the bottleneck, scaling them up to 2x64GB nodes to ensure there is no backpressure from ES that is limiting the throughput.
* Following config options need be aligned for high throughput: `queue.mem.events`,  `queue.mem.flush.min_events`, `queue.mem.flush.timeout`, `output.elasticsearch.worker`, `output.elasticsearch.max_bulk_size`

**Test Setup:**

micro setup: test 2m 20 5 5 --agents 2 --throttle 100 --timeout 10s --stream
all other APM sizes: test 2m 20 5 5 --agents 12 --throttle 1000 --timeout 10s --stream 
ES 6.4.3, 2 x GCP.DATA.HIGHCPU.1, 64GB RAM
APM: 6.5 9d7d8ad2923ddb128541a770815bf8ad9df28649

**Results**

APM | throughput | CPU usage | RAM usage | config opts
-- | --  | --| --| --
512MB, 1 CPU | 593 / sec | 25% | 300MB | -E queue.mem.events=32 -E queue.mem.flush.min_events=10 -E queue.mem.flush.timeout=1s -E output.elasticsearch.worker=10 -E output.elasticsearch.max_bulk_size=10 -E setup.template.settings.index.number_of_shards=2
4GB, 1 CPU | 3329.22 / sec | 100% | 600MB | -E queue.mem.events=1024 -E queue.mem.flush.min_events=512 -E queue.mem.flush.timeout=1s -E output.elasticsearch.worker=10 -E output.elasticsearch.max_bulk_size=100 -E setup.template.settings.index.number_of_shards=2
8GB, 2 CPU | 5289.29 / sec | 200% | 644 MB | -E queue.mem.events=16000 -E queue.mem.flush.min_events=500 -E queue.mem.flush.timeout=1s -E output.elasticsearch.worker=16 -E output.elasticsearch.max_bulk_size=500 -E setup.template.settings.index.number_of_shards=2
16GB, 4 CPU |  8649.95 / sec | 380% | 1.3GB | -E queue.mem.events=32000 -E queue.mem.flush.min_events=1000 -E queue.mem.flush.timeout=1s -E output.elasticsearch.worker=32 -E setup.template.settings.index.number_of_shards=2

**Conclusion**
APM Server is rather CPU heavy than memory heavy for default payloads and in default cases. 
Vertical scaling of APM Server requires to properly adapt config settings and to ensure ES output is not limiting. If settings are properly set the throughput scales almost linearly with scaling the CPU and memory.

**Comment by simitt** [comment]
Thanks to @elastic/apm-server and @urso for valuable input.

**Comment by simitt** [comment]
related blogpost from beats https://www.elastic.co/blog/how-to-tune-elastic-beats-performance-a-practical-example-with-batch-size-worker-count-and-more

**Comment by urso** [comment]
> related blogpost from beats elastic.co/blog/how-to-tune-elastic-beats-performance-a-practical-example-with-batch-size-worker-count-and-more

^ Special thanks to @ismael-hasan
