### ISSUE TITLE
Add sync property to spans

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-server#1523]
Certain operations in some languages could be executed synchronously or asynchronously and it would be useful to have this indicated on the span.

For example in the frontend applications we can create http requests that are executed synchronously and this could have negative influence on the performance of the page.

We should add `sync` property to spans:

```
{
  "sync": Boolean (optional)
}
```
----
UPDATE

The `sync` property should be searchable therefore it should be indexed!

cc @elastic/apm-agent-devs

**Comment by simitt** [comment]
@jahtalab how urgent is this? Are there also UI changes necessary to leverage this information?

**Comment by jahtalab** [comment]
@simitt , I wouldn't say it's urgent but it's an important field so I'd prefer to get it in as soon as possible.

Yes, I will create an issue for Kibana once this property is defined in the apm-server schema.

**Comment by simitt** [comment]
Should this be searchable and/or aggregatable, so we have to index it?

**Comment by jahtalab** [comment]
Yes, it should be searchable, I have updated the description!

**Comment by sqren** [comment]
In the future we will need to support spans that start and/or end after the parent transaction has ended. We have previously called these "async spans". Examples are queues. 
The kind of async spans suggested in this issue is a different concept. Have we thought about whether those two terminologies collide?

**Comment by roncohen** [comment]
For future reference, asked here as well: https://github.com/elastic/apm-dev/issues/328#issuecomment-440285377

**Comment by roncohen** [comment]
for future reference, I've copied the following from a discussion that happened elsewhere: 

I took a look at the OpenTracing span relationships to see if that relates to this `async` field:  They have FollowsFrom and ChildOf. The difference is that with ChildOf: 

 > the parent Span depends on the child Span in some capacity

whereas that's not the case for FollowsFrom: https://github.com/opentracing/specification/blob/master/specification.md#references-between-spans

I think the two concepts are unrelated: To my understanding, the OT concept "ChildOf" means the parent cannot _end_ before the child end because it depends on something the child returns/produces. While our `context.async` denotes if the "main thread" is blocked while the child executes. In other words, when you have "ChildOf" async can be both true and false, but with FollowsFrom "async" isn't so useful.

**Comment by watson** [comment]
@roncohen I agree that the two concepts are unrelated, but I just wanted to correct a potential misunderstanding related to "ChildOf":

> To my understanding, the OT concept "ChildOf" means the parent cannot end before the child end because it depends on something the child returns/produces. 

As far as I understand it, this isn't a requirement of the "ChildOf" relationship. E.g. if you look at the valid timing diagrams for "ChildOf", you'll see that "Child Span D" ends after its parent span.

The example used here says that a parent span can have a deadline for when it expects a result from the child. If the child fails to deliver the result within the deadline the parent can choose to end before the child.

So the "ChildOf" relationship is just signaling intent rather than actual timing.
