### ISSUE TITLE
Docs: Update Tuning section to show v1/v2 differences

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-server#1537]
> For everything related to tuning and config options we need some strategy to point out what to tweak and which options to use when agents talk Intake v1 vs. agents talking intake v2, e.g. if somebody uses a ruby agent with intake v1 and a nodejs agent with intake v2, then both - the deprecated and the newly introduced config options - should be set properly.

**Comment by simitt** [comment]
This looks like the right place to collect thoughts on new sections for trouble shooting in Intake v2:
* Explain and increase `apm-server.rum.event_rate` settings: The rate limiter was bound to number of _requests_ per second per ip in v1. Since with v2 the agents make use of long running requests (default 10s) and flush as many events over a single request as possible, the rate limiter has changed to be bound to number of _events_ sent per second per ip. If the rate limit is hit while events on an established request are sent, the request is not immediately terminated. The intake of the events is only throttled to `event_rate.limit`, which means that the events are queued and processed slower. Only when the allowed buffer queue is also full, the request gets terminated with a `429 - rate limit exceeded` http response. If an agent tries to establish a new request, but the rate limit is already hit, a `429` will be sent immediately.

**Comment by bmorelli25** [comment]
closed with #1576
