### ISSUE TITLE
document ILM in APM Server

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1545]

**Comment by graphaelli** [comment]
# An example ILM configuration

The following configuration will create a new index for spans every day or for every 50gb of spans, which comes first.  Each index will be retained for 10 days.  Additional configuration for error, metricset, transaction retention should be straightforward - policies can even be reused if there is overlap, say between errors and transactions.

To follow along locally, adjust this setting first, as the default ILM interval is only every 10 minutes.  This **value** should not be part of the official documentation, but probably good to link to https://www.elastic.co/guide/en/elasticsearch/reference/6.x//using-policies-rollover.html#using-policies-rollover where it is described.

## Step 0. Make ILM run much more often than the 10 minute default
```
PUT /_cluster/settings
{
  "transient": {
    "indices.lifecycle.poll_interval": "10s"
  }
}
```

## Step 1. Setup the apm-$version-* index template
```
./apm-server setup --template
```

## Step 2. Set up a policy for spans

To follow along locally, add a `"max_docs": 50` to the rollover actions to see them trigger without waiting very long.

```
PUT _ilm/policy/apm_span_policy
{
  "policy": {
    "phases": {
      "hot": {
        "actions": {
          "rollover": {
            "max_age": "1d",
            "max_size": "50gb"
          }
        }
      },
      "delete": {
        "min_age": "10d",
        "actions": {
          "delete": {}
        }
      }
    }
  }
}
```

## 3. Set up the ILM index template
```
PUT _template/apm-6.6.0-span-ilm
{
  "order": 2,
  "index_patterns": ["apm-6.6.0-span-*"],
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 1,
    "index.lifecycle.name": "apm_span_policy",
    "index.lifecycle.rollover_alias": "apm-6.6.0-span"
  }
}
```

## 4. Create the index + alias
```
PUT apm-6.6.0-span-000001
{
  "aliases": {
    "apm-6.6.0-span":{
      "is_write_index": true 
    }
  }
}
```

## 4b. Verify ILM index template was applied
```
GET apm-*-span/_settings
```

## 5. Start apm-server with modified configuration

Trim off the date template from each branch, so that apm-server is always writing to the same place per event type.  That place is the `is_write_index` alias created previously.

```
--- apm-server.yml
+++ apm-server.ilm.yml
@@ -410,23 +410,23 @@
       when.contains:
         processor.event: "sourcemap"
 
-    - index: "apm-%{[beat.version]}-error-%{+yyyy.MM.dd}"
+    - index: "apm-%{[beat.version]}-error"
       when.contains:
         processor.event: "error"
 
-    - index: "apm-%{[beat.version]}-transaction-%{+yyyy.MM.dd}"
+    - index: "apm-%{[beat.version]}-transaction"
       when.contains:
         processor.event: "transaction"
 
-    - index: "apm-%{[beat.version]}-span-%{+yyyy.MM.dd}"
+    - index: "apm-%{[beat.version]}-span"
       when.contains:
         processor.event: "span"
 
-    - index: "apm-%{[beat.version]}-metric-%{+yyyy.MM.dd}"
+    - index: "apm-%{[beat.version]}-metric"
       when.contains:
         processor.event: "metric"
 
-    - index: "apm-%{[beat.version]}-onboarding-%{+yyyy.MM.dd}"
+    - index: "apm-%{[beat.version]}-onboarding"
       when.contains:
         processor.event: "onboarding"
```

## 5b. Monitor ILM Status as events flow
```
GET apm-*/_ilm/explain?human
```

## 5c. Monitor index status too
```
GET _cat/indices/apm*?v
```
