### ISSUE TITLE
Run some basic benchmarks on RUM endpoint

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1547]
* make APM Server endpoint configurable in hey-apm https://github.com/elastic/hey-apm/issues/71
* run basic benchmark test for RUM endpoint 
* check horizontal and vertical scaling
* benchmark performance when sourcemap is uploaded

**Comment by jalvz** [comment]
Closing for same reason as: https://github.com/elastic/hey-apm/issues/71

Benchmarking sourcemaps could be interesting, but I think we should do that from inside (go bench), and just scoped to that: processing errors with and without sourcemaps.

But since we didn't hear from customer, I would not think this is a real issue.
