### ISSUE TITLE
Prevent APM Server from trying to load dashboards. 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1905]
As reported by @marius-dr the APM Server throws an error and stops working when the configuration file contains `setup.dashboards.enabled: true`. 
While all dashboard related options have been removed from the APM Server cmds and documentation and `yml` files have been updated to not mention dashboards at all in combination with APM Server, the logic to try and load the dashboards is still inherited from beats. 

This leeds to APM Server throwing an error as no dashboards are bundled with the server any longer. 

Having a quick look, I don't see an option to prevent this from happening in APM Server itself. This would require changes in libbeat. Right now we could only add some hardcoded check to not load dashboards when beat is apm. @urso do you think this would qualify for another _supporter_ similar to index setup? 

Generally my approach is that it is ok to fail if users use some undocumented, unsupported functionality that is simply inherited from beats. This case is different though, as users will still have this option set in their yml files, as it is supported up until 7.0.

**Comment by urso** [comment]
> do you think this would qualify for another _supporter_ similar to index setup?

APM and Beats have different requirements when it comes to 'Elastic stack setup'. I'm actually considering to redo template generation (also allowing for different template by index name) and introduce an 'Elastic Stack' supporter in general.

There is no 'good' hook for you to tell if this setting is enabled or not. Given the current code base you maybe have some options:
1. try to set `setup.dashboards.enabled: false` via config overwrites
2. Use the IndexSupporter. This one actually gets the raw config + so you can check for other settings and use `cfgwarn.Removed...` and return an error. This hack depends on the implicit execution order of index support and dashboard loader.
3. Introduce 'Elastic stack' supporter in libbeat. The stack supporter will assimilate ILM and Index supporter.

I did try to create a ConfigSupporter as well, but found it quite hacky and difficult to untangle due to configs being overwriting/updated all over the place. I thought IndexSupporter was good enough, so dropped it. Maybe we can give this another try, as this will allow you to overwrite config loading and warn/adjust any settings before libbeat actually sees them.

All in all, I see the 'supporter' approach only as a temporary approach, allowing apm-server to diverge some default behavior from the other Beats now, instead of waiting for some more bigger refactorings.
But long term I'd prefer us untangling libbeat features even more, so you can better compose wanted functionality in the future. This will allow apm-server diverge even more in default behavior/feature-set in comparision to the other Beats, while reusing what Beats provide.

**Comment by roncohen** [comment]
fixed temporarily now. We still need a solution that is viable longer term

**Comment by roncohen** [comment]
More composability sounds great @urso. Thanks for weighing in here.
