### ISSUE TITLE
Move user_agent information derived by user agent pipeline to root key. 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1960]
Currently when applying the user agent pipeline, the user agent information sent by backend agents is handled differently than the user agent information derived from the RUM agent. In both cases the user agent information is retrieved from the headers. 

For the RUM agent the information is directly fetched from the http request from the agent to the server when enriching the events with additional meta data. This information is then stored as root level key `user_agent` when applying the user agent pipeline.

Backend agents send the user agent information as part of the `context.request.headers` information. Currently applying the user agent pipeline leads to store the information under `context.request.headers.user_agent`. The `headers` should not be manipulated by the agents or the server, but reflect the original headers monitored by the agents. 

In both cases the `user_agent` information should end up in the same place and be indexed, when applying the user agent pipeline.

**Comment by simitt** [comment]
@elastic/apm-agent-devs while at this change, it would be great to have more strict rules on the Intake API level for `headers`. Basically only to allow for following options: 
```
"headers": {
    "user-agent": "Mozilla Chrome Edge",
    "foo": "a,b,c",
    "bar": ["a","b","c"]
}
```

Would this be possible to add as restriction on the Intake API without breaking any of the agents in the current version? 
- [ ] go
- [ ] java
- [ ] node
- [ ] python
- [ ] ruby
- [ ] rum

**Comment by watson** [comment]
It's currently possible for it to send up numbers instead of strings.

Normally this shouldn't happen, but there's technically nothing blocking a developer from say parsing the string value of the `content-length` into a number and overwriting the original string value. The Node.js would then just take that as is. I'll make sure this doesn't happen in the future by converting all values to strings or array of strings. But technically this might break someone out there.

I'm leaning strongly towards treating this as an error though and just require people to upgrade to the latest Node.js agent as I don't want this to be a blocker for making this change. That's why I also checked the box above.
