### ISSUE TITLE
Apache proxy timeout

### ISSUE THREAD

**Issue by tflorac** [elastic/apm-server#1998]
Hi,
I'm trying to configure an Apache proxy in front of my APM server to filter IP addresses which are allowed to connect to my APM server and add authentication.
With the Java agent, and simple Apache ProxyPass/ProxyPassReverse configuration, I always get 408 proxy timeout errors (which I don't get while using the Python agent, or when connecting directly to APM server).
I tried to increase ProxyTimeout but this doesn't seems to work!
So which Apache configuration should I use to be able to use Java agent?
Best regards,
Thierry

**Comment by graphaelli** [comment]
Hi @tflorac!  Questions are better suited for our [discussion forums](https://discuss.elastic.co/c/apm) as you'll get a wider audience.  I'd suggest including any relevant configuration/version for and logs from Apache along with versions of the agents, apm-server so that we may reproduce the issue.

You may also want to +1 https://github.com/elastic/apm-server/issues/1266 to help us prioritize that issue and subscribe to it for updates.
