### ISSUE TITLE
Document upgrade instructions for Linux packaged installations

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#2022]
There are 2 relevant aspects for users upgrading a rpm or deb package from 6.x to 7.0:

1 - During the 7.0 install, users will be prompted with a warning saying that the install is about to overwrite `/etc/apm-server/apm-server.yml`, and offered several actions (overwrite, don't overwrite, see the diff)
The right thing for them do to is:
- back up their current config file
- accept overwrite from the 7.0 install
- bring to the new config file whatever changes they wanted from the old file.

2 - With https://github.com/elastic/apm-server/pull/1833 we changed the ownership of apm-server files for rpm/deb packages.
Users upgrading from 6.x to 7 should do that manually after installing the new version by running `chown -R apm-server:apm-server /var/lib/apm-server /var/log/apm-server /etc/apm-server/apm-server.yml` in their apm-server hosts.

@graphaelli correct me if I'm wrong or have any additions.

**Comment by graphaelli** [comment]
It turns out 2 is only true some times - on centos 7 that happened automatically.  I'm tempted to have that be automatic for deb too - what do you think?  The original decision was a bit arbitrary, erring on the side of not surprising users.  Perhaps though users would be more surprised that the permissions are not fixed automatically?  The change to make this happen [would be minor](https://github.com/elastic/apm-server/blob/7.0/packaging/files/linux/deb-post-install.sh.tmpl#L6).

**Comment by roncohen** [comment]
agreed @graphaelli 👍 let's see if we can make the change.
