### ISSUE TITLE
Document installing from APT/YUM repos

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#210]
We should include instructions on how to install APM Server from the Elastic APT/YUM repositories similar to https://www.elastic.co/guide/en/beats/filebeat/current/setup-repositories.html

**Comment by dedemorton** [comment]
We need to make a final decision about how we are going to handle docs that are shared between apm-server and beats/libbeat.

The doc build will let us pull in the files from beats/libbeat, but the versions will always need to be in sync. For example, the doc build for master will build the apm-server docs from the master branch and pull in the shared files from the master branch in the beats repo.  The same will be true of 6.0, 6.x, etc. 

The other approach (making copies of the content) isn't good IMO because we'll have to maintain duplicated content. The content will most definitely get out of sync and won't benefit from quality improvements made in the other repo.

@elastic/apm WDYT?

**Comment by ruflin** [comment]
apm-server will be in sync with the release with the release. Right now our 6.0 branch depends on 6.x from beats. From my perspective both approaches work. I kind of prefer the copy approach so everything that will be "shipped" is in the apm-server repo. I don't worry about the copy part as we can easily automate that. Already now we have a script that copies over certain doc files beats, we only need to add the new ones to it.

**Comment by dedemorton** [comment]
If we can automate the copy, then that should work. Do you think I should refactor the docs in libbeat so that all the shared content appears in an `include` folder or something similar to make the copy easier? Right now, libbeat/docs contains a mix of shared files plus content for the platform reference. You probably only want to copy over the shared files, no?

**Comment by ruflin** [comment]
If possible I would want to only copy over the shared files. Having all of them in on directory I think would be great not only to making copying the files easier, but also make it obvious when working with the files, that they are shared among to beats. Not sure how big of an effort and how breaking such a change is?

**Comment by dedemorton** [comment]
> Not sure how big of an effort and how breaking such a change is?

Not a big effort. We just need to move the files to a sub-directory and then update the paths wherever they are referenced. The actual URLs that users see won't change. The biggest inconvenience would be later on if we decide to backport other doc changes. Maybe that's not an issue since we are so far along with 6.0.

**Comment by ruflin** [comment]
If we make this change, we should backport it to 6.0 as apm-server releases currently depend on it.

**Comment by roncohen** [comment]
As far as I can tell, "just" having these two would be a great start:
https://github.com/elastic/beats/blob/master/libbeat/docs/repositories.asciidoc
https://github.com/elastic/beats/blob/master/libbeat/docs/shared-docker.asciidoc

I'm leaning towards just copying those to the APM Server repo for now to get us started.

Longer term, I'm not sure if the auto-copy approach discussed above is going to work.  I don't think APM Server is necessarily going to use the same documents as metricbeat, filebeat etc. and I think some of the documents will end up diverging. 

Ultimately, the ideal approach would be if the apm-server was able to cherry-pick some docs from the libbeat repo that would be kept in sync through the usual update mechanism that @ruflin mentioned. That would give us the freedom to pick for ourselves. If you agree, any ideas how we get there @ruflin @dedemorton ?

**Comment by ruflin** [comment]
I think there are two options to get there: We add these two files to the copy script to keep them up-to-date. Or to get started we copy them over manually and link them. The part we need to make sure is that all the variables used in this file are defined. Should we take this directly into a PR?
