### ISSUE TITLE
Request Per Minute [APM] visualization uses wrong field 

### ISSUE THREAD

**Issue by jjfalling** [elastic/apm-server#214]
Request Per Minute [APM] should use transaction.result as the filter field for the status code (or APM is sending the wrong field ;) )

**Comment by watson** [comment]
Yes, I think you're right. The dashboards are probably using `context.response.status_code` at the moment. This field might not always be present (whereas `transaction.result` should be).

The `transaction.result` field is a string and there's no rule that it should conform to look like an HTTP status code.

Also, even if the two fields are both present, there's no guarantee that they are the same. I think we even discussed if `transaction.result` - in case of an incoming http request - should be converted from the string `200` to `2xx` already in the agent instead of when viewed in Kibana?

**Comment by simitt** [comment]
@beniwohli and @watson what do you think about making `transaction.result` a mandatory field? This way we could always rely on this field for visualizations.

**Comment by beniwohli** [comment]
I'm ok with that!

**Comment by watson** [comment]
Sounds like a good idea 👍

**Comment by simitt** [comment]
Thank you @jjfalling for bringing this up, we changed the dashboards to use `transaction.result` now.
