### ISSUE TITLE
User.username is being mapped to User.name

### ISSUE THREAD

**Issue by dsanders11** [elastic/apm-server#2182]
Despite the agents (such as elastic/apm-agent-python and elastic/apm-agent-rum-js) sending `username` to the `apm-server`, it appears that the server is instead mapping the username to the `name` field internally. This makes the Kibana APM UI incorrect since it will show no username, and instead put the name in username.

It seems the internal mapping doesn't have the concept of username, from a quick glance. Using search on the APM UI seems to suggest there's `name` and `full_name`, and to search by username you need to search by `name`.

Seems like quite a few wires are crossed here.

**Comment by simitt** [comment]
Thanks for reporting @dsanders11! The APM Server is indeed mapping `user.username` to `user.name` from `7.0` on to be aligned with [ECS](https://www.elastic.co/guide/en/ecs/current/ecs-user.html#_user_field_details). The `user.name` is shown in Kibana. 
I'll forward a note to @elastic/apm-ui though that it is confusing to still show a field for `user.username`, since it is not going to be filled anymore.

**Comment by sqren** [comment]
This has been fixed in https://github.com/elastic/kibana/pull/35150 and will go out in 7.2.

<img width="1284" alt="Screenshot 2019-05-20 at 11 46 28" src="https://user-images.githubusercontent.com/209966/58012575-14707000-7af5-11e9-9212-9157473ef1bb.png">

**Comment by graphaelli** [comment]
Thanks @sqren, closing since this has been resolved.
