### ISSUE TITLE
Nothing to view on APM tab on Kibana.

### ISSUE THREAD

**Issue by ariansz** [elastic/apm-server#2362]
I'm logging some transactions using apm-server version 6.8.0. I can see my apm-* indices on Kibana (version 7.2) index management and I have added the following lines to the kibana.yml file:

```
apm_oss.errorIndices: apm-*
apm_oss.onboardingIndices: apm-*
apm_oss.spanIndices: apm-*
apm_oss.transactionIndices: apm-*
```

adding these lines to the issues already present here seemed to have helped people who had the same issues on Kibana.

I ran this query through DevTools:
```
GET apm-*-error-*,apm-*-transaction-*/_search
{
  "size": 0, 
  "query": {
    "match_all": {}
  }
}
```

Here's my result:

```
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 55,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}
```

Yet when I open the APM tab on Kibana all I see is "Looks like you don't have any APM services installed. Let's add some!"

I'm on MacOS and using elastic version 7.2.0 and I installed everything through homebrew.

**Comment by graphaelli** [comment]
Hey @ariansz, apm-server 6.7-6.8 can ingest into elasticsearch 7.x but the 7.x APM UI is not compatible with that format as noted in the [compatibility matrix](https://www.elastic.co/support/matrix#matrix_compatibility).  You can use the upgrade assistant to migrate data indexed with apm-server 6.8.0 into a format 7.2.0 APM UI can display until you're able to upgrade apm-server.

Closing this out since this is documented.  Please drop by the [forums](https://discuss.elastic.co/c/apm) if you need any additional support.
