### ISSUE TITLE
Include service.environment on spans

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#2471]
Today we don't include `service.environment` on spans. We do include `service.name`. Unfortunately, due to the existence of `service.environment`, using only `service.name` does not fully identify a service. We should add `service.environment` so it's also included in all spans.

**Comment by simitt** [comment]
At the moment `service.name` can be overwritten on a per event basis in the Intake API. I assume adding `service.environment` to a span also requires allowing to overwrite this property, as it could lead to inconsistent `service` data otherwise. @felixbarny afair you have been asking for overwriting fields back then, do you agree on allowing to overwrite per event?

**Comment by felixbarny** [comment]
There’s no option in the Java agent to allow for multiple environments in one JVM and we don’t have plans for that.
