### ISSUE TITLE
Vendoring libbeat and using development tools, packaging of elastic/beats

### ISSUE THREAD

**Issue by kvch** [elastic/apm-server#2560]
I have already taken a look at `update-beats` target and `update_beats.sh`. I see that you put dev-tools of Beats under `_beats` folder. I have a few questions. :)

- How much do you use packaging of beats?
- What issues do you have when vendoring libbeat? How do you work around it?
- Is there anything that would make using libbeat and our dev-tools easier for you?

**Comment by jalvz** [comment]
Thanks for reaching out! You have very generic/broad questions, so I'll try to answer them the best that I can...

> How much do you use packaging of beats

afaik we are packaging apm-server in the same way as other beats, plus/minus a couple customizations. Notability we don't have reference.yml files, we don't create DMG packages, and we don't have any x-pack features (we do have x-pack builds thou).
We also use an specific, separated yml file for the docker distributions (I think other beats handle that differently).

On Jenkins we automatically trigger the package target on master, release branches and beats updates pull requests, but we can also trigger it manually eg. if we mess around with the mage file.
Also, before each release I usually run it locally and have a look and do some manual tests. 

I am happy with how packaging works now with mage and we can do the customizations that we need. For such a big change the ride has been smooth, so congrats are in order to everyone involved!


> What issues do you have when vendoring libbeat?

Speaking for myself, I can mention a couple of things:

One is that it is quite time consuming and prone to errors. We are a small team and we don't have the bandwidth to review closely everything we sync from beats, so we scroll trough and just go with it. 
Consider #2559 for instance: that is 450k lines changed, and in this case Gil was smart enough to figure out that vendor.json was left out of sync and fixed it. But it is very easy to miss things (for a case of an important detail we missed and impacted our users see #2096, which highlights another complication: it can be very hard for you as well to know what can break us!). 

Another (bigger, related) issue is that we get things we do not want. 
Sometimes we can opt out of features, sometimes we can not (or it is quite hard to do and requires changes in both libbeat and apm-server). But even opting out of things requires to notice those things in first place, which it might as well not happen (see point above). 
And example of this are subcommands: maybe some we don't want (like export dashboards), some conflict with how we do things (ILM), etc. I would love if we could opt in into features, instead of opting out. So instead of having logic to remove / workaround conflicts with beats subcommands, have logic to create them and import the ones we want.
Another way in which we often opt out of things is simply to not document it (like the Redis output), which is not so great.


> Is there anything that would make using libbeat and our dev-tools?

Long term? Modularizing beats and making libbeat look more like a library and less like a framework :)

Recently we started to sync beats changelogs and I am not sure yet how much it is helping. Many times I feel that the descriptions are too terse and I don't have the context. We definitely are syncing much more stuff than needed (we are only interested in libbeat changes), so maybe a changelog file just for libbeat would help a bit... 
Some more context in the libbeat changelog would surely help, I rather read a very detailed changelog than 10k's of lines of code :)

This is what it comes to mind now, but I will think more about it!

**Comment by jalvz** [comment]
@kvch is there something else we can do that here? Some clarification or follow up?
Ill close this otherwise

**Comment by kvch** [comment]
No, thank you. I was just requesting information to make sure we won't interfere with your processes when we move to go modules.
