### ISSUE TITLE
[ACM] Implement RUM endpoint

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#2694]
The RUM endpoint will provide the same functionality as as the backend endpoint with following differences:

- No secret token.
- Rate limit.
- CORS handler.

The existing rate limit and allowed origin settings used for the intake endpoint will be applied here.

___

As pointed out by @graphaelli , this endpoint could be abused to expose backend configuration data. To mitigate that, the UI will include a `rum-enabled` checkbox for users to confirm that a given service is instrumented by the RUM agent. 
apm-server will receive that value from Kibana as a boolean, and it will only return configuration if it is true.
____

Currently backend agents derive their polling interval from the `Access-Control-Max-Age` header. We can have a different value for the RUM endpoint.

**Comment by jalvz** [comment]
cc @jahtalab @vigneshshanmugam

**Comment by jahtalab** [comment]
While investigating the caching mechanism, I discovered a few other challenges both related to the CORS handling. One issue is that the `etag` header is not exposed to the client unless it is explicitly allowed by the server, the server can allow exposing `etag` by adding `Access-Control-Expose-Headers: ETag` header to the response.

The second issue is related to adding the `If-None-Match` header to the request to `/config/v1/agents` since `If-None-Match` header is not a CORS valid header therefore the browser automatically issues an OPTIONS request to the server to verify the server is prepared to accept this header. The first problem is that at the moment the `/config/v1/agents` endpoint does not respond to OPTIONS request which makes the subsequent request fail as well.

However, the bigger issue here is that now the overhead of fetching configs is doubled since at least two requests are necessary (one OPTIONS and one GET) to fetch configs. After a call with @jalvz , we decided to send the value for `If-None-Match` as a query string to avoid this problem.

**Comment by jahtalab** [comment]
@jalvz , what is the final name for the `If-None-Match` query string? 
Also, can we use all lowercase characters for that?

**Comment by jalvz** [comment]
@jahtalab how would you like to call it?

**Comment by jahtalab** [comment]
Something like `ifnonematch` or similar, I don't have strong opinion though.

**Comment by jalvz** [comment]
Cool, lets just go with that.
