### ISSUE TITLE
Add messaging related fields to Intake API and map to ES

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#2697]
Add `context.message` to the Intake API for `span` and `transaction` and map to appropriate ES fields. 

* `context.message.queue.name`
* `context.message.topic.name`
* `context.message.body`
* `context.message.headers`

more details in https://github.com/elastic/apm/issues/143

Things to clarify:
* sent for `transaction` only or also for `span` events? (see https://github.com/elastic/apm/issues/143#issuecomment-530287968)
* Fields in ES: advise with ECS team on naming, even when not directly added to ECS, ensure the fields are chosen in a way to not conflict with future developments in ECS. 
* Do any of the fields need to be indexed, if so, which ones? Clarify the use cases for the information.

**Comment by axw** [comment]
@eyalkoren already tested with a real application using the Java agent, and we haven't touched the messaging support since it landed and 7.6 BC's were built, so I did not test with a "real" app.

Instead, I started a branch to add support for messaging to the Go agent: https://github.com/elastic/apm-agent-go/pull/707. This is incomplete, but it's complete enough to test with. I wrote a little test app which reports a transaction and span each with dummy message context, and it worked as expected.

Transaction metadata:
![image](https://user-images.githubusercontent.com/843579/72975384-b0344780-3e0b-11ea-8b17-f599ee2befce.png)

Span metadata:
![image](https://user-images.githubusercontent.com/843579/72975405-baeedc80-3e0b-11ea-8aba-acbf67a65b80.png)

**Comment by mdelapenya** [comment]
Hey @axw is it possible to automate that little test app in the project? Does it make sense?

If so we can use that app to define a minimal setup for the end2end tests that we want to add

**Comment by axw** [comment]
@mdelapenya I haven't merged the messaging support into the Go agent, so not yet at least. I think for end-to-end tests it would be better to use a real message queue + instrumentation, rather than faking it.

**Comment by mdelapenya** [comment]
Ok, makes sense having a real service for the end2end test. If the test application is a fake/mock/stub, wdyt about having at the unit/integration tests level, as part of the build? I'd follow this path if an only if the test execution is fast enough.

**Comment by axw** [comment]
I don't think that's a useful exercise, and is not in line with what we do today. We already have integration tests that quickly exercise the relevant code paths. The reason I wrote the test app was just to test with the built artefact, since we lack the end-to-end testing with a real app.
