### ISSUE TITLE
Config endpoint should avoid setting empty value on Etag header

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-server#2916]
Currently, if no configuration exist for a given service name the APM server response from the config endpoint includes `Etag: ""`. While this doesn't create issues, it's better to just avoid sending this header if no configuration exist.

**Comment by jalvz** [comment]
@felixbarny argued that that is OK, for as long we return `304` on subsequent requests when nothing changes. @felixbarny are you OK with just removing the empty `Etag`, or do you still prefer the other approach?

I'm fine either way.

**Comment by felixbarny** [comment]
I don't really care about the content of the Etag header. But if the config did not change, I'd expect the server to return a `304 Not Modified`. Because that case is so common, I would really prefer it if the server could deal with conditional gets of empty configurations.

**Comment by simitt** [comment]
@jahtalab how would that work if there is no config available. Afaiu for the first request the server responds with `200` and `Etag:""`, which allows the agent to include the `Etag:""` in the next request and the server can answer with a `304` now. 

If the server only sends a `200` and no Etag, the agent would either not include the empty Etag in the next request, leading to another `200` instead of a `304` from the server, or it would be required to implement some special handling.

**Comment by jahtalab** [comment]
It seemed strange to me seeing an empty value for the etag header, even though it's valid, from the first look it's not clear whether it's intended to be like that or not. If this is the intended behaviour for the empty config, then I would suggest to use a constant string instead.

**Comment by axw** [comment]
Confirmed this works. The initial response is `200 OK` with `Etag: "-"`, and subsequent responses (where the agent passes `If-None-Match: "-"`) are `304 Not Modified` with `Etag: "-"`.
