### ISSUE TITLE
missing node attributes in ILM policy

### ISSUE THREAD

**Issue by mwasilew2** [elastic/apm-server#3287]
Hello,

APM server is most likely to be used in logging clusters. These clusters often use a hot-warm architecture. In fact, the ILM policy available in the repo already uses hot and warm phases. However, the policy does not specify node attributes to be used when moving shards to the warm phase. This can result in situations where shards for apm indices are not moved to warm nodes, but instead stay on hot nodes (despite being in the warm phase of ILM).

One undesired consequence of that is the fact that the apm shards unnecessarily contribute to shard imbalance. This is particularly problematic when for example a node is added to the cluster or when a node leaves the cluster temporarily.

Having node attributes defined in the warm phase of the ILM policy would ensure that shards in warm phase are always moved to warm nodes. I'll follow up this issue with a PR with an attempt at fixing this.

Thanks!

**Comment by simitt** [comment]
Adding the `allocate` action requiring a data node with attribute `warm` to the default policy would most probably break several setups. We cannot assume that all setups have nodes with a `warm` attribute. For setups where this is not the case the transition into the warm phase would get stuck, not allowing to move the shard to another node while it is also disallowed to remain on the current node. 

IMO the right way to move forward with this is to 
* add a note to the docs about adding the proper node attributes when leveraging hot-warm clusters (cc @bmorelli25)
* customize the used policy to include the `require` action whenever it makes sense. Since 7.5 you can [customize policies](https://www.elastic.co/guide/en/apm/server/7.5/ilm.html#custom-ilm-configuration) via APM Server configuration.

@mwasilew2 what do you think, does customizing the ILM policy via apm-server.yml work for you instead of changing the default policy?

**Comment by mwasilew2** [comment]
@simitt it does yes, I agree, it's better to default to a safer behaviour, ie not use node attributes, and document it, rather than by default break all set-ups without the warm attribute

Thanks for reviewing!
