### ISSUE TITLE
Add fingerprint processor for use in service maps

### ISSUE THREAD

**Issue by dgieselaar** [elastic/apm-server#3335]
Currently Kibana is using a composite aggregation on 5 fields of spans for collecting trace ids that it should inspect to build a service map. These fields are:

- `service.name`
- `service.environment`
- `destination.address`
- `span.type`
- `span.subtype`

Fingerprinting these fields on ingest (i.e., some kind of serialization) would allows to either use a composite agg with one source, which is seemingly faster, or a terms agg, which has even better performance plus removes some limitations around composite aggregations (like nesting it under a sampler aggregation).

APM Server could install this fingerprinting processor as it already controls the `apm` pipeline.

Additionally the field in which the fingerprinted value is stored should be added to the apm-* template mapping.

I've previously used `connection.hash`, but there's probably a better field name. Here's an example of the processor (again, probably room for improvement):

```json
{
  "apm_connection_hash" : {
    "description" : "sets a connection hash based on various fields",
    "processors" : [
      {
        "script" : """
      def address = ctx.destination?.address;
      
      if (address == null || address == "") {
        return;
      }
      
      def hash = new ArrayList();
      def fieldsToHash = new HashMap();
      fieldsToHash['span.type'] = ctx.span?.type;
      fieldsToHash['span.subtype'] = ctx.span?.subtype;
      fieldsToHash['service.name'] = ctx.service?.name;
      fieldsToHash['service.environment'] = ctx.service?.environment;
      fieldsToHash['destination.address'] = address;
      
      for (entry in fieldsToHash.entrySet()) {
        if (entry.getValue() != null) {
          hash.add("{"+entry.getKey()+":'"+entry.getValue()+"'}");
        }
      }
      
      ctx.connection = new HashMap();
      ctx.connection.hash = hash.join('/');
    """
      }
    ]
  }
}
```

**Comment by beniwohli** [comment]
Stupid question, but would it make sense to calculate the fingerprint in APM-Server instead of installing another ingest pipeline? The APM Server already does a similar thing with error grouping keys

**Comment by dgieselaar** [comment]
@beniwohli I like it! I think _someone_ brought it up previously, but I forgot. It does make it a little harder to add if for historical data though. With a processor it's pretty easy to for instance to add it for the last 24hrs on Kibana startup. Probably not much of a concern though?

**Comment by simitt** [comment]
@beniwohli what do you see as the advantage of adding it to the server's logic instead a pipeline?

**Comment by beniwohli** [comment]
@simitt less complexity, mostly. Setting up the pipeline may fail for some reason, or the user could modify/delete it by mistake.

Precedence is another, the Server is already doing exactly this kind of work (copying and modifying fields, calculating hashes based on fields etc.)

Performance, too, but that's just a hunch. I'd guess that doing this in Go is quicker than in a scripted language.

I didn't consider the reindexing case that @dgieselaar brought up. Is that something we'd recommend users to do or is it more of a nice to have for us during development?

**Comment by jalvz** [comment]
Does the fingerprint needs to be configurable or extensible in some way? 
Because if not, I think too that calculating it in the server would be less ceremonious (just my 2c)

**Comment by simitt** [comment]
IMO we should figure out a general strategy when to use ingest pipelines, including default and final index pipelines, and when it makes sense to implement a custom solution in the APM Server, basically being clear about the advantages/disadvantages for both solutions and having performance comparison.

**Comment by jalvz** [comment]
> general strategy when to use ingest pipelines, including default and final index pipelines, and when it makes sense to implement a custom solution in the APM Server

A good rule of thumb is to pick the simplest option that fulfils the requirements.

**Comment by simitt** [comment]
There's less obvious ones, I'd argue we should have in mind when making decisions, e.g. reusing logic from existing pipelines instead of re-implementing everything in the server, allowing flexibility for users to add/remove/adjust pipelines, using pipelines to be ECS compatible and only diverging from beats when there is a good reason for it (e.g. [adding final pipelines](https://github.com/elastic/beats/pull/14001)), considering performance impacts, etc.

I don't want to derail this issue though. So let's figure out the general parts aside of this.

**Comment by jalvz** [comment]
Sure!:

> reusing logic from existing pipelines instead of re-implementing

That fails in the "simplest option" part: reusing is simpler than re-implementing

> allowing flexibility for users to add/remove/adjust pipelines

That fails in the "fulfil requirements" part: there is no point in making an argument for that case if it not required/valuable in itself.

> only diverging from beats when there is a good reason

A good reason, again, like simplicity or suitability for requirements (like we always did)

It seems we agree on this, then. 

So: does this fingerprint need to be configurable somehow? Does it have to be enabled or disabled in particular circumstances? It is processing historical data needed?

**Comment by ycombinator** [comment]
I came across this issue while looking at another issue, so I don't have all the necessary context. But I wanted to just mention, in case it wasn't known already, that Beats (libbeat) has a `fingerprint` processor since 7.6.0, in case that might be applicable to the use case being discussed in this issue: https://www.elastic.co/guide/en/beats/filebeat/master/fingerprint.html.

**Comment by axw** [comment]
The APM Server team discussed this a bit more, and a couple of additional points were raised:
 - There are some exotic use cases where users translate logs to the APM schema, or otherwise produce APM data without going through the APM Server. This is a +1 for using ingest node.
 - Pushing more work onto ingest node means it is increasingly centralised, potentially creating a performance bottleneck. If we had APM Server co-located with instrumented services, then we can distribute costs. Kinda +1 for implementing in APM Server, but depends on the deployment model.

**Comment by simitt** [comment]
I looked into the beats fingerprint processor and recommend against using it for following reasons:
* the processor uses a hash function: for the servicemap fingerprint using a hash function is not important, it should just be guaranteed that the same input values result in the same fingerprint value for grouping. Using a simple base64 encoding for the string value is sufficient.
* the processor should always run by default. Libbeat processors can be configured in the `apm-server.yml`, but to enable dedicated processors in code we would need to overwrite the [`Processing:      processing.MakeDefaultObserverSupport(false)`](https://github.com/elastic/apm-server/blob/master/cmd/root.go#L85), to include the fingerprint processor. This could be done with the current implementation, but adds additional complexity that is not necessary when implementing the logic directly in the APM Server. 

To the extent of my knowledge the processor should not be configurable. The resulting fingerprint string is solely used for the servicemap feature. The less it can be customized the better. Only if servicemaps are disabled in Kibana it might make sense to disable the fingerprint calculation.
Based on this reasons I suggest to not add the calculation to the default ingest processors, but rather implement the logic directly in the APM Server for now and then revisit if the logic should be moved to a final processor once final index processors are supported by libbeat. There is a PR in beats discussing how to add and use [final index processors](https://github.com/elastic/beats/pull/14001). 
Adding it to the default pipeline would allow users to remove the processor. For setups with customized pipelines, the new processor might not automatically be added when updating. The servicemap feature would be broken until the processor is added, and the fingerprint would then only be calculated for newly processed events. 
Switching from an APM Server implementation to final pipelines later should be backwards compatible. The only scenario where it might be problematic is when the output is not Elasticsearch, but  e.g. to logstash or Kafka, as the pipelines might not be setup. For such scenarios it is already recommended though to first run `apm-server setup` as the index template would be missing otherwise. Running the full setup command would also set up the pipelines.
