### ISSUE TITLE
make release-manager fails

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#3417]
As follows on macOS.  This also happens on linux:

```
$ make release-manager-snapshot

_beats/dev-tools/run_with_go_ver /Library/Developer/CommandLineTools/usr/bin/make release
./build/darwin/mage package
2020/03/03 13:45:44 Found Elastic Beats dir at /go/src/github.com/elastic/apm-server/_beats
>> Building apm-server.yml for linux/amd64
>> Building apm-server.docker.yml for linux/amd64
Generated fields.yml for apm-server to /go/src/github.com/elastic/apm-server/fields.yml
package ran for 3.119154221s
Error: failed to run "mage -f -goos=linux -goarch=amd64 -compile build/mage-linux-amd64: exec: "mage": executable file not found in $PATH"
failed to run "mage -f -goos=linux -goarch=amd64 -compile build/mage-linux-amd64: exec: "mage": executable file not found in $PATH"
failed to run "mage -f -goos=linux -goarch=amd64 -compile build/mage-linux-amd64: exec: "mage": executable file not found in $PATH"
```

**Comment by axw** [comment]
This will of course be because of the recent Makefile changes, and `mage` not being installed globally. I think the root cause is this:

https://github.com/elastic/beats/blob/f6869827a18b8ae0feb8aa5956f4042502675241/dev-tools/mage/crossbuild.go#L164-L170

We can either:
 - revert to installing mage globally
 - install mage into a build dir and add it to $PATH
 - change beats/dev-tools to use the magefile library, rather than shelling out

The last one is my preference.

**Comment by axw** [comment]
I think that'll end up being a pain - I'll look at building locally and adding to $PATH for now.
