### ISSUE TITLE
[CI] Investigate Python packages install errors

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-server#3661]
We seem some error in logs related to the installation of some packages (autopep8 and others), most of the time it doesn't affect the build bu some times the build fails and we suspect is related. We have to investigate what this error is about and how to resolve it.

```
02:44:51    Running setup.py bdist_wheel for autopep8: started
02:44:51    Running setup.py bdist_wheel for autopep8: finished with status 'error'
02:44:51    Complete output from command /tmp/tmp.5zwrYpkdZB/python-env/build/ve/linux/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-dlwm_ele/autopep8/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpfz_7vai0pip-wheel- --python-tag cp36:
02:44:51    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
02:44:51       or: -c --help [cmd1 cmd2 ...]
02:44:51       or: -c --help-commands
02:44:51       or: -c cmd --help
02:44:51    
02:44:51    error: invalid command 'bdist_wheel'

02:44:52    ----------------------------------------
02:44:52    Failed building wheel for docopt
02:44:52    Running setup.py clean for docopt
02:44:52    Running setup.py bdist_wheel for ipaddress: started
02:44:53    Running setup.py bdist_wheel for ipaddress: finished with status 'error'
02:44:53    Complete output from command /tmp/tmp.5zwrYpkdZB/python-env/build/ve/linux/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-dlwm_ele/ipaddress/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp6hsbqx9spip-wheel- --python-tag cp36:
02:44:53    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
02:44:53       or: -c --help [cmd1 cmd2 ...]
02:44:53       or: -c --help-commands
02:44:53       or: -c cmd --help
02:44:53    
02:44:53    error: invalid command 'bdist_wheel'
```

**Comment by cachedout** [comment]
I believe this may have to do with the `wheel` module either not being installed before the `pip install -r requirements.txt` command begins or it is there but outdated.  Both of these scenarios are a little surprising since they should be there as a result of the virtualenv being created, so I'm not sure why this is only happening periodically.

Still, I think we can probably resolve this by just adding `wheel` to the `requirements.txt` file. Unfortunately, this is where things start to get tricky.

The `requirements.txt` in question is coming from `libbeat`. So, the first thing I want to do is to cc: @mikemadden42 to see if he's seen this error happen on the Beats CI anywhere or if we can search for it there. If it's also a problem there, then we'll know that we should upstream this fix there and then pull those changes back into `apm-server`.

**Comment by kuisathaverat** [comment]
this start happens after the change from Python 2 to Python 3, we also changed the way to make the virtual environment from virtualenv to 'python -m venv', and I found this https://github.com/elastic/beats/blob/master/Makefile#L159 for some reason `autopep8` is manually installed on a fixed version.

**Comment by cachedout** [comment]
It's not just `autopep8` that is failing, though: https://apm-ci.elastic.co/job/apm-server/job/apm-server-mbp/job/master/471/consoleFull

We might try modifying that line in the Makefile to install `wheel` before the rest and see if the problem goes away.

**Comment by cachedout** [comment]
@kuisathaverat Could you please point me to where you made the change from `virtualenv` to `python -m venv`? That might be the right place to test a fix.

**Comment by kuisathaverat** [comment]
The new virtual env creation is on Beats https://github.com/elastic/beats/blob/master/Makefile#L158 the APM Server uses it from here https://github.com/elastic/apm-server/blob/8b4a6452451ce1f7e7ff338ed5f32e334e47dd84/Makefile#L257-L261

**Comment by cachedout** [comment]
I have put up a PR that I believe should fix the issue here: https://github.com/elastic/beats/pull/18745
