### ISSUE TITLE
Using a custom index and custom ILM does not work

### ISSUE THREAD

**Issue by AEGEGE** [elastic/apm-server#4023]
Hello!

I am using APM server, elasticsearch, kibana, version 7.7.1, Due to the large number of business lines, I divided APM server into several different groups, and configured different user-defined indexes, mainly for the convenience of reporting. However, due to the increase of users, my single index exceeds 200g, so I want to automatically scroll the index through ILM.

My custom index format is apm-test-transaction-2020.07.23-000001，I am in elasticsearch Configuration in API

`PUT /%3Capm-test-transaction-%7Bnow%2Fd%7D-000001%3E
{
  "aliases": {
    "apm-test-transaction": { "is_write_index": true }
  }
}`

The alias APM test transaction is created and the template of APM is matched
`{
  "apm-test-transaction-2020.07.23-000001" : {
    "aliases" : {
      "apm-test-transaction" : {
        "is_write_index" : true
      }
    },
‘’‘’‘’
"settings" : {
      "index" : {
        "lifecycle" : {
          "name" : "apm-test",
          "rollover_alias" : "apm-test-transaction"
        },
‘’‘’‘’`

After configuration, I tested and found that the maximum index size I set for ILM was reached，index is rollover，
Generate apm-test-transaction-2020.07.23-000002,But apm-server will continue to write to apm-test-transaction-2020.07.23-000001, and will not write the newly generated index.pls help me，thanks！

**Comment by axw** [comment]
Hello @AEGEGE! We use the Github repository for verified bug reports, pull requests, apm-server specific feature requests, etc.

For questions such as yours, please head over to our official [Discuss forum](https://discuss.elastic.co/c/apm). You will reach a wider audience, get help from the broader community, and maybe learn how others solved similar problems.

If it turns out there is a bug in the product, then we can come back here and open an issue.
