### ISSUE TITLE
Document how to create API Keys for Agent auth using the ES REST API

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#4135]
We should extend https://www.elastic.co/guide/en/apm/server/current/api-key.html to explain how to use the Elasticsearch REST API to create API Keys for agent auth. See https://discuss.elastic.co/t/unable-to-create-apikey-in-apmserver-after-installing-7-9/246659/11

**Comment by bmorelli25** [comment]
We do mention this [briefly](https://www.elastic.co/guide/en/apm/server/current/api-key-settings.html) in the reference docs, but I totally agree we should build this into the main workflow doc. I'll add these changes to https://github.com/elastic/apm-server/pull/4130 since I'm already working with the document.
