### ISSUE TITLE
Sourcemaps: consider using `binary` field type

### ISSUE THREAD

**Issue by beniwohli** [elastic/apm-server#420]
When displaying sourcemap documents in Kibana/Discover, Kibana more or less throws up its hands and gives up (sourcemaps can be multi-megabyte large).

AFAIK, Discover doesn't try to display [`binary`](https://www.elastic.co/guide/en/elasticsearch/reference/current/binary.html) fields, which would solve this. It is also semantically the better choice IMO, as sourcemaps should be pretty much opaque for Elasticsearch.

We should also consider using gzip. The space savings should be pretty huge*, and the time savings in transferring the data from ES to apm-server should easily make up for the time used to decompress, especially on one of the lower gzip levels.

As an example, the sourcemap from https://github.com/elastic/opbeans/ is 

 * 4.3Mbyte uncompressed
 * 1.1Mbyte at gzip level 1
 * 996kbyte at gzip level 4
 * 924kbyte at gzip level 9

--
\* maybe not, due to built-in compression of Elasticsearch.

**Comment by epixa** [comment]
I'm not sure what fields.yml is, but just a general idea: the source filters in kibana are set on the index pattern saved object, so whatever mechanism you're using to create the index pattern for apm data is the mechanism you'd want to modify to specify source filters.

**Comment by simitt** [comment]
@epixa I might be misunderstanding this, but in the `discovery` section both, indexed and non indexed fields, show up. However, one can only set the source filter exclude option for indexed fields, as the others are not even part of the index pattern. 
How can one ensure that non-indexed fields do not show up in the discovery part?

**Comment by epixa** [comment]
I may not understand the question, but the discover section shows all fields from [_source](https://www.elastic.co/guide/en/elasticsearch/reference/6.1/mapping-source-field.html), which is the original JSON document used at index time minus any of the fields that were explicitly [excluded](https://www.elastic.co/guide/en/elasticsearch/reference/6.1/mapping-source-field.html#include-exclude) from source at index time.  Since this will include both indexed and non-indexed fields, [source filtering](https://www.elastic.co/guide/en/elasticsearch/reference/6.1/search-request-source-filtering.html) applies to both.

**Comment by simitt** [comment]
I was referring to your comment about using the index pattern for adding source filters. 

> the source filters in kibana are set on the index pattern saved object, so whatever mechanism you're using to create the index pattern for apm data is the mechanism you'd want to modify to specify source filters.

So far we only have fields defined in the index pattern that should get indexed. But probably we just have to include also non-indexed fields there and set the source filtering accordingly.

**Comment by epixa** [comment]
Thanks for clarifying, I think I better understand where you're coming from.  Ultimately, while we store the "intention" for source filtering on index pattern itself, we're applying those rules to requests using the source filtering feature of elasticsearch, which will affect both indexed and non-indexed fields that are stored in _source.  So in theory, even if you don't have a field in the index pattern cache in Kibana, the filtering should still work at request time.

However, I'm not really sure what sort of validation is in place on Kibana's side for deciding what is a valid source filter to save with the index pattern.  If Kibana rejected that because fields from the cache didn't match, then we probably need to make a change to Kibana to make that more flexible.

**Comment by beniwohli** [comment]
@simitt I manually added these source filters, and that makes them disappear from Discover:

![](https://s.woh.li/0ov76nXq.png)

In #432, only one filter is necessary, I guess.

What remains is to figure out how we can set this filter programmatically through libbeat / `fields.yml`

**Comment by simitt** [comment]
Thanks @beniwohli I had concerns adding the filters to the generated `index-pattern`. 
However, I have a better understanding now and I think it should be possible to add it via the index pattern, thank you @epixa and @beniwohli for elaborating on this.
