### ISSUE TITLE
When max unzipped limit is hit, APM Server responds with unhelpful 'unexpected EOF' error

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#438]
It's possible to send gzip compressed payloads to APM Server. When the APM Server receives a compressed payload it will stop decompression after `MaxUnzippedSize` bytes. The purpose of the limit is to guard against zip bombs. If the payload is not fully read after `MaxUnzippedSize` bytes, it will result in an unhelpful EOF error when the JSON parsing of the payload is attempted.

The error is `Problem validating JSON document against schema: unexpected EOF`

We should emit a more helpful error message if the limit is hit.

**Comment by beniwohli** [comment]
I think the main reason for seeing this problem is either too many transactions per minute, or too many transactions with large amounts of traces. The former problem can be solved by increasing the send frequency (which all agents support AFAIK). For the latter problem, we don't have a solution yet. A few options are proposed in #280
