### ISSUE TITLE
Fill descriptions for fields without

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#4450]
Fields with missing descriptions can be found here: https://github.com/jalvz/apm-server/tree/generate-package-fields/apmpackage/apm/0.1.0

**Comment by axw** [comment]
In addition to scanning the markdown, I wrote this small program to cross-check:

```python
import yaml
from yaml.loader import SafeLoader

def check_fields(fields, name):
    for field in fields:
        check_field(field, name)

def check_field(field, name):
    name += "." + field.get("name")
    if field.get("type", "group") != "group" and "description" not in field:
        print("missing description in {}".format(name))
    check_fields(field.get("fields", []), name)

for fields in yaml.load(open("build/fields/fields.all.yml"), Loader=SafeLoader):
    key = fields["key"]
    if key.startswith("apm"):
        check_fields(fields["fields"], key)
```

(I also tried and failed to do this in [CUE](https://cuelang.org/). I'll give it another shot some time...)

@jalvz is it intentional that "internal metrics" (e.g. destination service metrics) are excluded from the docs?

**Comment by simitt** [comment]
Checked the [exported fields docs](https://www.elastic.co/guide/en/apm/server/master/exported-fields.html) and the _Exported Fields_ section when installing the APM integration.
