### ISSUE TITLE
Add actual source to stacktrace frame when applying sourcemapping

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#457]
Add the `pre_context`, `post_context` and `context_line` information when sourcmap mapping is applied to a stacktrace frame of an incoming request.

**Comment by simitt** [comment]
@roncohen @jahtalab where do we get this information from? Should we force customers to upload the source code with with the source maps or do we download them from somewhere when an Url is included in the sourcemap?

**Comment by jahtalab** [comment]
@simitt , As we discussed in our meeting, There're two options to get the source one is git integration which @roncohen said we're not going to do and the other one is a property in the sourcemap file called `sourcesContent` which contains the source code for each file (see [Source map spec](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k)).

We should check if this field exist on the source map file before trying to use it.

I don't it's necessary to add this field to source map validation that is done before uploading, since the sourcemap is still useful without it.
@roncohen any thoughts?

**Comment by jalvz** [comment]
as a matter of fact, from opbeat id say that a lot of times they dont set it because that would basically make their code public. it shouldnt be required

**Comment by jahtalab** [comment]
I think leaking the code is not an issue here since people are uploading the sourcemap to their own elasticsearch instance. In Opbeat days we automatically downloaded sourcemaps from the user's servers which required the sourcemap to be available publicly.

**Comment by jahtalab** [comment]
@alvarolobato @roncohen , Can we prioritize this again? Are there any blockers?

**Comment by graphaelli** [comment]
wasn't this done in #647 ?
