### ISSUE TITLE
Tail-sampling: service-specific policies are always matched before catch-all

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#4616]
**APM Server version** (`apm-server version`):

7.11.0 BC1

**Description of the problem including expected versus actual behavior**:

Tail-sampling policies which define a `service.name` are matched before those without, even if defined later in the list of policies. This breaks the intention that policies are matched in the order they are defined.

**Steps to reproduce**:

1. Run APM Server with the following config:

```
apm-server:
  sampling:
    tail:
      enabled: true
      interval: 10s
      policies:
      - trace.name: no_spans
        sample_rate: 0.5
      - service.name: goagent
        sample_rate: 0.1
```

2. Send 1000 transactions with `transaction.name: no_spans`, and `service.name: goagent`.
3. We should end up with 500 (50%) traces sampled, but due to the bug only 100 (10%) are sampled.

**Comment by jalvz** [comment]
Following the instructions as is doesn't work, I got an error `Error processing configuration: invalid tail sampling config: no default (empty criteria) policy specified`
It took me a while to understand that the error is intentional, running apm-server with `"apm-server.sampling.tail.policies=[{trace.name: \"no_spans\", sample_rate: 0.5}, {service.name: \"goagent\", sample_rate: 0.1}, {sample_rate: 0.0}]"` instead, then it does work as expected
