### ISSUE TITLE
Introduce support for hot-reloading config without restarting

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#5039]
At the moment, APM Server will internally restart the HTTP/gRPC server, aggregators, sampler, etc. whenever a configuration change is received. This is implemented by using `libbeat/cfgfile.NewRunnerList`: https://github.com/elastic/apm-server/blob/0e09aa69022be69e15345b21d891ed3ec7c3f067/beater/beater.go#L191

As we progress with integration into Fleet, dynamic reconfiguration will be increasingly common. e.g, support for agent central config (https://github.com/elastic/apm-server/issues/5018) and source maps (https://github.com/elastic/apm-server/issues/5002), as well as future features such as tail-based sampling will all rely on dynamic reconfiguration.

Restarting everything just because agent configuration has changed is clearly not ideal. We should investigate ways to improve this, so we restart only the services that require it. For example, when `apm-server.host` changes, naturally the server needs to restart.

**Comment by stuartnelson3** [comment]
Based on the options from the redesign (https://github.com/elastic/kibana/issues/91412) I've made a list of the config options that should be reloadable. If they require a server restart (such as TLS) that is also noted.

- maximum size of request header
- idle time
- read time
- shutdown time
- write time
- max event size
- custom headers
- max api keys for agent auth
- capture personal data
- service config / default service environment
- golang expvar support (route under /debug/vars)
- simultaneous connections (Triggers restart because it's a wrapper around listener)

RUM:

- enable
- custom headers
- access-control-allow-headers
- custom http response headers
- rate limit per IP
- rate limit cache size
- allowed service names

TLS: should trigger a server restart
- enable
- server cert path
- server cert key path
- supported protocol versions
- cipher suites
- curve types

Not controlled by apm-server config screen:
- agent_config
- sourcemaps

**Comment by stuartnelson3** [comment]
closed by #5911

**Comment by axw** [comment]
Tested in https://github.com/elastic/apm-server/pull/5911.
