### ISSUE TITLE
Syntax error when starting APM server

### ISSUE THREAD

**Issue by BlagoCuljak** [elastic/apm-server#5051]
**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including server configuration, agent(s) used, etc.  The easier you make it
for us to reproduce it, the more likely that somebody will take the time to
look at it.

 1. Download and extract APM agent from https://artifacts.elastic.co/downloads/apm-server/apm-server-7.12.0-darwin-x86_64.tar.gz
 2. Change the apm-server.yml, output.elasticsearch: ->  hosts: ["<es_url>"]
 3. Try to start the service, sudo ./apm-server -e

~/apm-server-7.12.0-darwin-x86_64$ sudo ./apm-server -e                        
**./apm-server: 1: Syntax error: "|" unexpected**
[https://prnt.sc/111j50f](https://prnt.sc/111j50f)

**Comment by axw** [comment]
@BlagoCuljak it sounds like there's a formatting issue in your `apm-server.yml`, rather than a bug in the code. Please open a new topic at https://discuss.elastic.co/c/apm and someone will respond there. If you can share your full `apm-server.yml` when you do, then we may have a better chance of identifying the issue. Thanks!
