### ISSUE TITLE
Default ILM template for APM uses hot/warm

### ISSUE THREAD

**Issue by cconboy** [elastic/apm-server#6170]
>>  it looks like APM is setting up a hot/warm ILM template out of the box that is used by default. This means that every new deployment in ESS will have a warm tier and it will auto-create itself whenever Autoscaling is enabled. Can we switch this default ILM policy for APM to be hot-only? Otherwise every single deployment will end up with a Warm tier, even if it’s just for a few APM docs.

If I understand correctly, changing to hot only would lead to growth in hot indices. APM is using hot/warm intentionally as the best available strategy, and has been doing this for >1year, although the interaction with autoscaling is newer. I also understand there to be changes coming in 8.0 that indirectly fix this issue.

**Comment by pcsanwald** [comment]
hey @cconboy thanks for opening the issue. The issue we've seen in the past is that customers are surprised when a warm tier is scaled into existence because of an ILM policy, which can happen for relatively small amounts of data. A representative salesforce case is 00766551, although there are plenty more examples.

The reason this is coming up in the context of autoscaling, is that autoscaling is the thing that is creating the warm tier from a customer's perspective, and since we are talking about enabling autoscaling by default for new deployments, we expect to see a good amount of warm tiers getting autoscaled into existence if we keep our ILM policy configuration as it is today. We have two options:

1) Decide to keep our defaults as-is, and accept that this will be a point of confusion with some customers that support will need to deal with.

2) Change our default policy to hot only or something similar.

**Comment by cconboy** [comment]
@graphaelli @Mpdreamz

**Comment by simitt** [comment]
Thanks for bringing this to our attention. The main reason why we chose to introduce hot/warm by default was that data become less interesting over time and therefore older data are not actively indexed and are expected to appear less frequently in searches.
If the default policy is causing issues, and a hot only default policy is preferred, I don't see a reason why we couldn't change that (preferably from 8.0 on). Could you help me understand though why warm tiers are a source of confusion and less desirable than keeping all data in the hot tier? 

> I also understand there to be changes coming in 8.0 that indirectly fix this issue.

From 8.0 on, APM Server will only write to data streams. There are no current plans to revisit the ILM policy, so as soon as apm data are ingested, I don't think the switch to data streams would change anything.

**Comment by graphaelli** [comment]
> There are no current plans to revisit the ILM policy

In that case I misinformed @cconboy on this point, I see now that it is indeed the same with data streams.  I agree changing this with 8.0+/data streams is tidy and users can customize their policies until then.

I assume the ILM policy is not updated on upgrade for data streams, just like for classic indexes, so this would only impact new installations and not upgrades?

**Comment by axw** [comment]
The server team has discussed this, and we have agreed to make the change for the APM Fleet integration that will go GA in 7.16. In 8.0, data streams will be the only way APM Server indexes data, and so the updated ILM policy will be the default.

We're not currently planning to change this for _standalone_ in 7.16, as it would be a breaking change in behaviour. I think we can debate this part.

**Comment by pcsanwald** [comment]
tagging @henningandersen as well to keep me honest in below comment:

> Could you help me understand though why warm tiers are a source of confusion and less desirable than keeping all data in the hot tier?

the problem is basically that users are surprised that a warm tier is autoscaled into existence after 30 days, [relevant thread here](https://elastic.slack.com/archives/CT9C8SN66/p1631538128016500). So it's more that users do not realize their topology is going to change in 30d, and it can scale up a tier to deal with a relatively small amount of data.

**Comment by simitt** [comment]
> I assume the ILM policy is not updated on upgrade for data streams, just like for classic indexes, so this would only impact new installations and not upgrades?

The ILM policy _is_ updated on apmpackage upgrade. The updated policy is applied as soon as the datastream rolls over next time.
