### ISSUE TITLE
Metrics duration not rounded as expected

### ISSUE THREAD

**Issue by cauemarcondes** [elastic/apm-server#6249]
@sqren created [a tool](https://github.com/sqren/synthbeans-node) to generate predictable APM data. When executed it generates one service with two transactions and these transactions should have rounded statistics, such as latency, throughput, and failed transactions rate.

For the transaction documents the values are rounded.
<img width="2880" alt="Screen Shot 2021-09-27 at 12 47 20 PM" src="https://user-images.githubusercontent.com/55978943/134951433-1a28370a-b9b3-4ad8-86f9-a9712dae54b5.png">

But when I filter to show only the metrics documents the values are not rounded.
<img width="2880" alt="Screen Shot 2021-09-27 at 12 48 25 PM" src="https://user-images.githubusercontent.com/55978943/134951602-6425aa87-3dc9-4f36-989b-03f9159568b8.png">

I ingested data in this cluster https://synthbeans-data.kb.us-central1.gcp.cloud.es.io:9243 and the credentials can be found [here](https://p.elstc.co/paste/tf5jB391#E3YR6FgnfgmPTv+NFERBEW5qUoLYqmzujz86oSy3-hH)

**Comment by axw** [comment]
Are you expecting an exact value of 4000ms in the metric docs?

Transaction durations are aggregated using [HDRHistogram](http://hdrhistogram.org/), and we emit documents using the discrete histogram buckets rather than exact values aggregated. The nature of this approach is that we sacrifice perfect accuracy for storage savings.

**Comment by sqren** [comment]
@dgieselaar started https://github.com/dgieselaar/elastic-apm-generator which bypasses this problem by producing the metric documents and ingesting them directly to Elasticsearch (not through APM Server).

If we are happy with that solution we can close this.

**Comment by axw** [comment]
> bypasses this problem

What's the goal? It is expected that APM Server produces metrics which aren't exactly aligned to the input event durations. Is there any risk we'll miss edge cases in our testing due to the misalignment with that and how the synthetic metrics generation?

**Comment by dgieselaar** [comment]
> What's the goal? It is expected that APM Server produces metrics which aren't exactly aligned to the input event durations. Is there any risk we'll miss edge cases in our testing due to the misalignment with that and how the synthetic metrics generation?

This is purely (at least, for now) for API tests where we want to move from snapshot testing to logical testing. E.g., I want to write instructions to generate 100tpm of transactions over 15 minutes, and then I want to write a logical test that asserts that the throughput returned by the API is exactly 100. We're also considering using the library directly in API tests (rather than through a generated archive), and in that case requiring APM Server as a component would complicate things. That being said, I'm trying not to tightly couple the library to Elasticsearch as the only output mechanism, so we can consider routing through APM Server in the future.

**Comment by axw** [comment]
Sounds reasonable. I'll close this, as I don't think there's anything we should be changing in apm-server either way.
