### ISSUE TITLE
Timestamp of original event is disregarded for transaction/span metrics

### ISSUE THREAD

**Issue by dgieselaar** [elastic/apm-server#6254]
**APM Server version** (`apm-server version`):

7.15

**Description of the problem including expected versus actual behavior**:

Currently, when APM Server creates metricsets from transactions and exit spans, it will use its own timer to group and timestamp metrics, without taking the timestamp of the original event into account. This means that if data is delayed, it will be indexed into Elasticsearch as if it was actually observed at a (much) later time. This is inaccurate, and it makes it hard to compare results based on transaction events and transaction metrics. Additionally, it means we cannot use APM Server when generating synthetic data which timestamp lies in the past, which would help us in creating more useful test data sets.

Related: https://github.com/elastic/apm-server/issues/6249

**Steps to reproduce**:

- Run https://github.com/sqren/synthbeans-node/ and compare the results of transaction metrics and transaction events, the former should cover a smaller time range.

**Comment by simitt** [comment]
Summarizing what @dgieselaar and I have discussed so far:

The transaction/span metrics are created by aggregating multiple events, which don't have the exact same timestamp. When the event's timestamps should be respected, we might need to add a timerange to the aggregation key. The event's timestamp could be rounded to define the lower and upper limit, for example creating a bucket of a 1 minute duration. This would ensure that (in-memory) aggregation keys stay unique, and every recorded event can be added to exactly one metricset or lead to creating a new metricset. Since the duration buckets would be independend of the configured `aggregation.transactions.interval`, multiple metric documents with the same timestamp and aggregation key might be ingested in ES. This shouldn't be a problem, and can already occur when running multiple APM Servers. 
Overall this might lead to more ES documents with less histogram values per document, but the aggregation would be more accurate.

**Comment by axw** [comment]
> Since the duration buckets would be independend of the configured aggregation.transactions.interval

Should they be independent? The interval could serve two purposes:
 - to configure the timer for periodically publishing aggregated metrics
 - to calculate the time range for the metrics aggregation key

> multiple metric documents with the same timestamp and aggregation key might be ingested in ES. This shouldn't be a problem, and can already occur when running multiple APM Servers.

Even if we use the interval as described above, this could still be the case if events come in late. I agree, this would not be a problem.

**Comment by simitt** [comment]
>>Since the duration buckets would be independend of the `configured aggregation.transactions.interval`

>Should they be independent? 

If they weren't independent, then I don't see how we could create buckets that are independent of the events' timestamps. And as soon as the first event's timestamp defines the bucket duration, we might end up having two overlapping buckets. Which I believe would cause issues and potentially sparse buckets. 

Example:
`configured aggregation.transactions.interval: 20s`
e1:  11:07:45  -> bucket duration `11:07:35-11:07:55`
e2:  11:07:30  -> would not fall into the first bucket, creating a new one for `11:07:20-11:07:40`, overlapping with the first bucket

**Comment by axw** [comment]
What I had in mind was that we would align time to multiples of the interval. i.e. use https://pkg.go.dev/time#Time.Truncate

Using your example of 20s interval:
- e1: 11:07:45 -> time range 11:07:40-11:08:00
- e2: 11:07:30 -> time range 11:07:20-11:07:40

(We would need to choose one of the bounds for `@timestamp`; I'd go with the start time.)

**Comment by dgieselaar** [comment]
> (We would need to choose one of the bounds for @timestamp; I'd go with the start time.)

++, this would be my expectation as well

**Comment by simitt** [comment]
sounds good
