### ISSUE TITLE
[DOC] Document the APM Server Monitoring API

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/apm-server#6451]
In the documentation [there is a reference](https://www.elastic.co/guide/en/apm/server/current/monitoring-metricbeat-collection.html#configure-shipper) of how to enable the HTTP endpoint to allow Metricbeat `beats` module to collect stats & status of APM Server.

There is a dedicated section for APIs, but we do not include the Monitoring (except server info): https://www.elastic.co/guide/en/apm/server/current/intake-api.html

We should document the `/stats` endpoint.
Also, from the `apm-server.yml`, it seems the HTTP endpoint is experimental while we propose it as a GA solution to [monitor APM Server](https://www.elastic.co/guide/en/apm/server/current/monitoring-metricbeat-collection.html):
```
# apm-server can expose internal metrics through a HTTP endpoint. For security
# reasons the endpoint is disabled by default. This feature is currently experimental.
# Stats can be access through http://localhost:5066/stats. For pretty JSON output
# append ?pretty to the URL.
```

**Comment by axw** [comment]
> Also, from the apm-server.yml, it seems the HTTP endpoint is experimental while we propose it as a GA solution to monitor APM Server:

I don't know the original reason for that, but I'd guess that the endpoint is experimental because we don't want to maintain strict backwards compatibility; just enough compatibility to not break Metricbeat-based monitoring through upgrades.

The future is Fleet, and when you install an Elastic Agent you have the opportunity to enable metrics. Given this, I would prefer not to increase the guarantees we provide on this (essentially internal) API.

**Comment by simitt** [comment]
I agree with @axw to not change anything here. APM Server standalone will soon be deprecated, and Elastic Agent and Fleet will manage the APM Server. Exposing a metrics collection endpoint will then be configured via Elastic Agent configuration. 
@lucabelluccini are you ok with closing this issue?

**Comment by lucabelluccini** [comment]
Given the plans with the Agent & Fleet to manage APM Server, I am ok to close this issue. Thank you!
