### ISSUE TITLE
Combined transactions + errors endpoint

### ISSUE THREAD

**Issue by Qard** [elastic/apm-server#680]
Hey, so @watson and I were chatting at the Node.js Diagnostics Summit recently and were discussing the idea of auto-sending all transactions in the queue whenever an error occurs, so the UI could have all the data to display the full context of the error as soon as possible. That led to the idea that, because the rest of the data in the two endpoints is identical, we could simply have a merged endpoint and just send all the data in one request rather than two. What do you think?

**Comment by simitt** [comment]
Removing existing endpoints and combining them into one would be a breaking change. Thus, for `6.x` we would need to add an additional endpoint to enable this. 
First thing we do atm is creating a `TransactionHandler` or an `ErrorHandler`. I'd be fine with adapting this logic to be able to process transactions and errors within one request. But I'd like to get rid of the existing logic then to not make it unnecessarily complicated. 

Thus, I suggest to revisit a combined endpoint for version `7.x`, except the agents expect a huge performance improvement from this.
How about you still trigger sending the content of the transaction queue once an error is sent, so the customer would experience the same outcome?

**Comment by watson** [comment]
@simitt I'm not a Go expert to say it mildly, so I might think this is more simple than it really is. But wouldn't it be easy to just move all the logic to a new combined endpoint and simply have the two old endpoints being aliases of the new endpoint?

**Comment by simitt** [comment]
Everything's possible, and if we expect a gain from that we could of course refactor it. We'd still need to keep the existing endpoints around though and if we don't expect this to have a huge performance impact then I'd rather see it as an improvement that we could do as a breaking change in 7.x.

**Comment by watson** [comment]
I just found my self in a situation where I actually would have appreciated that all transactions where sent to the APM Server together with the errors: If an unhandled exception occurs, we send it to the APM Server and shut down the process. Any transactions still in the queue is lost forever. This means that the transaction under which the unhandled error occurred is lost as well and the transaction id referred to by the error is "invalid".

The agent can of course be updated to flush the transaction queue before shutting down, but I already feel bad holding it open while sending the error (as the node process is in an unknown state because of the unhandled exception), so I'd like if we could avoid making a 2nd http request. But it's of course easy to do if we need to.

**Comment by simitt** [comment]
Thanks for the additional explanation. I suggest we see if the other @elastic/apm-agent-devs would also benefit from this, so we can prioritize it.

**Comment by beniwohli** [comment]
@watson wouldn't adding transactions to an error payload heighten the risk that neither can be sent out before the runtime exits?

FWIW, the Python agent flushes the transaction queue on runtime exit, assuming the runtime is still in a state that allows it to happen.

**Comment by mikker** [comment]
From an API perspective I like the idea of a single intake endpoint 👍 

I also see why this could be a somewhat large change to make to `apm-server` so 7.0 sounds like a reasonable timeframe to me.

The Ruby agent also flushes the queue on exit but it doesn't exit on errors. So for now users have to wait the <= 10 seconds before transactions are flushed again.

**Comment by watson** [comment]
> wouldn't adding transactions to an error payload heighten the risk that neither can be sent out before the runtime exits?

@beniwohli I don't think so, but in reality I'd like to not do any asynchronous operation at all when an uncaught exception occurs.

I still think it should be possible to do nicely with very little change to the code base, but that's most likely just due to my limited understanding of our current server implementation

**Comment by simitt** [comment]
This brings up the question of how to handle a single failure in the response: drop the overall response or only drop the corrupted entry.

**Comment by simitt** [comment]
We can close this now as we are working on v2.
