### ISSUE TITLE
Extend transaction fields in transaction metrics

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-server#6843]
As initiated and discussed in this [discussion thread](https://github.com/elastic/apm/discussions/548) the transaction metrics documents should contain most of the transaction and metadata fields per default. 

Related/supercedes: https://github.com/elastic/apm-server/issues/6576

Tasks:
- [ ] Define a set of field that explicitly **should not** be included in transaction metrics
- [ ] Make APM server add all transaction fields (except the explicitly excluded ones) per default to the transaction metrics documents

**Comment by dgieselaar** [comment]
>  Make APM server add all transaction fields (except the explicitly excluded ones) per default to the transaction metrics documents

Are we sure this is a good idea?

**Comment by AlexanderWert** [comment]
@dgieselaar do you mind describing your concern [in here](https://github.com/elastic/apm/discussions/548) so we can continue the discussion on this topic? Thanks!

From the comment in the discussion thread there were no major concerns with that.

**Comment by simitt** [comment]
For completeness adding the initial request from https://github.com/elastic/apm-server/issues/6576#issue-1049891960:
>Transactions reported for AWS lambda functions populate the boolean fields faas.coldstart and faas.trigger.type.
Furthermore, the field service.runtime.name is required to determine whether a service is in a serverless context.
In order to derive additional, Lambda-specific insights it would be very useful, if the transaction metrics derived from transaction events in the APM could include the service.runtime.name, faas.coldstart and faas.trigger.type fields (when available) into the metric documents reported to Elasticsearch.

**Comment by marclop** [comment]
Resolved in #7033. There's a follow up issue (#7047) that captures the problems outlined in this issue.
