### ISSUE TITLE
Test aarch64 support for APM Server on 7.17

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#7477]
Right now APM Server is not officially supported on `aarch64` in `7.x`. Conduct manual testing for APM Server `7.17.0` on `aarch64` on Linux for the supported set of x86_64 linux distributions.

If no issues are uncovered, this should be added to the automated test scenarios.

**Comment by stuartnelson3** [comment]
Simple smoke test performed using stack@7.17.3, and then apm-server on two different distros on aarch64, ubuntu and redhat. These two distros were chosen because we currently package the apm-server as a .deb and .rpm.

Events were sent to both of these apm-servers and successfully indexed into elasticsearch, and showed up correctly in the apm-ui.
