### ISSUE TITLE
[Telemetry] OpenTelemetry usage telemetry

### ISSUE THREAD

**Issue by basepi** [elastic/apm-server#7532]
As we're adding support for [OpenTelemetry API bridges](https://github.com/elastic/apm/pull/516), it would be useful to know how much they're being used so we know whether to prioritize additional features in the bridge spec.

We can use `otel.span_kind` for this telemetry. All spans from the otel bridges should have `otel.span_kind` set. The APM Server is inferring this field for non-otel spans, but we could record telemetry information before this infer step takes place.

**Comment by simitt** [comment]
@basepi what exactly do you expect to be stored for telemetry purposes? At the moment the APM Server sets one of the following values `CLIENT`,  `SERVER`, `PRODUCER`, `CONSUMER` and `INTERNAL`, depending on the concrete values sent by the apm agents. 

> The APM Server is inferring this field for non-otel spans, but we could record telemetry information before this infer step takes place.

The fields are only populated if [`span.otel`](https://github.com/elastic/apm-server/blob/main/model/modeldecoder/v2/decoder.go#L1018-L1019) or [`transaction.otel`](https://github.com/elastic/apm-server/blob/main/model/modeldecoder/v2/decoder.go#L1242-L1247) is set. Field values are currently not derived for non-otel spans. 
Do you envision to prefix or postfix with a certain value so that the differentiation between otel bridge and native apm agents is still possible if populating this field for all events?

**Comment by basepi** [comment]
Oh, I guess I was under the impression it would be inferred for all spans, not just if `span.otel` or `transaction.otel` were set.

In that case, we can probably just use `span.otel`/`transaction.otel` as the source for telemetry.

Does the APM Server handle gathering the telemetry or do I need to open another issue elsewhere? I haven't done anything with telemetry in the past. (I also know that telemetry is a bit fraught right now and we may have to wait until telemetry v2)
