### ISSUE TITLE
Backend dependencies granularity: Add `span.context.service.target.*`

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#7715]
### Intake API
Extend the Intake API for spans to accept `span.context.service.target.name`(optional) and `span.context.service.target.type` (optional).

### Data scheme
Index `span.service.target.name` (`keyword`) and `span.service.target.type` (`keyword`) in an [ECS compatible](https://github.com/elastic/ecs/blob/main/schemas/service.yml) way (similar to `span.service.origin.*` fields).

--- 

Related follow up issue for further data processing https://github.com/elastic/apm-server/issues/7734 
Related issue for metrics calculation https://github.com/elastic/apm-server/issues/7745

**Comment by AlexanderWert** [comment]
@simitt I discussed this with @SylvainJuge this week. I would propose to split this into two step:
1. Intake API + Data scheme (we should aim for completing this in 8.3)
2. Data processing (stretch for 8.3)

**Comment by simitt** [comment]
Updated the title and split up into two issues.

**Comment by SylvainJuge** [comment]
I have updated https://github.com/elastic/apm/pull/627 to include the split in multiple "phases", this issue should cover at least a part of what is currently called "Phase 1".

One thing that wasn't clear yesterday when this issue was created is that there are some indirect implications in the dropped spans metrics, as a result I think we must also include it.
