### ISSUE TITLE
[Intake] `http.request.id`

### ISSUE THREAD

**Issue by basepi** [elastic/apm-server#7871]
I'd like to add [`request.id`](https://www.elastic.co/guide/en/ecs/current/ecs-http.html#field-http-request-id) to [`span.context.http` in the intake](https://github.com/elastic/apm-server/blob/4e5755408350f6868a1cf78270e0a358a81b989a/docs/spec/v2/span.json#L169-L174).

This comes from a [user request](https://github.com/elastic/apm-agent-python/issues/1524) to store the AWS Request ID in span context, which I think is very reasonable. `http.request.id` seems to be the closest fit in ECS.

Questions/thoughts welcome.

**Comment by basepi** [comment]
An alternative would be to use `span.context.response.headers` if this isn't considered a wide enough use-case to add to the intake.

**Comment by simitt** [comment]
Adding `request.id` sounds reasonable! Thanks for opening the issue.

**Comment by AlexanderWert** [comment]
right now the only case in which I see some value of `transaction.context.request.id` would be for AWS Lambda transactions. BUT: we already capture the request ID for lambda under `faas.execution`, so no need to duplicate this information. For `error.context.request.id` we would need to propagate the request ID to be able to attach it to errors (what we currently don't and cannot do because of missing baggage support).

So I would propose to only have it for `span.context.request.id` for now.
