### ISSUE TITLE
Document options for dealing with 503: Queue is full responses

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#800]
We need to document in which scenarios the `503: Queue is full` can occur and document which options users have to troubleshoot when it happens.

**Comment by bastbnl** [comment]
@roncohen I ran into a 503 error too but it had a different cause. I'm running apm-server behind nginx and I had to configure `client_max_body_size` on the location to make sure elasticsearch (which is behind nginx as well) accepted the body since nginx will return 503 when the request body is over a certain size:

```
2018/06/16 17:06:57 [error] 9134#9134: *58437 client intended to send too large body: 1337630 bytes, client: x, server: , request: "POST /_bulk HTTP/1.1", host: "x:9200"
```

It's really not caused by `apm-server`, but maybe this would save somebody time when using this fairly common deployment pattern.

Happy to create a PR with additional details on the documentation.
