### ISSUE TITLE
Standardize on where to store span peer info

### ISSUE THREAD

**Issue by watson** [elastic/apm-server#813]
Currently we don't have any place to store remote address information on a span (e.g. the host/port of a database span or a http request span).

I suggest we copy the OpenTracing approach as closely as possible to make future interoperability easy (the names doesn't matter, as long as we have the same fields). [OpenTracing uses tags](https://github.com/opentracing/specification/blob/master/semantic_conventions.md#span-tags-table) to encode this information. To follow our current scheme, we should place this information under the span context, i.e:

Property | Type | Notes
-- | -- | --
`peer.hostname` | string | Remote hostname. E.g., `"opentracing.io"`, `"internal.dns.name"`
`peer.ipv4` | string | Remote IPv4 address as a `.`-separated tuple. E.g., `"127.0.0.1"`
`peer.ipv6` | string | Remote IPv6 address as a string of colon-separated 4-char hex tuples. E.g., `"2001:0db8:85a3:0000:0000:8a2e:0370:7334"`
`peer.port` | integer | Remote port. E.g., `80`
`peer.service` | string | Remote service name (for some unspecified definition of `"service"`). E.g., `"elasticsearch"`, `"a_custom_microservice"`, `"memcache"`

Example:

```json
"context": {
  "peer": {
    "hostname": "example.com",
    "port": 80
  }
}
```

I'm not sure how much I like that port can be part etc of the hostname, but I guess there's some valid use-cases/concerns being covered by that.

Also I'm not sure I like the word `peer`, but I guess it's so that this can also contain information about an incoming request (something we currently reserve for transactions).

**Comment by simitt** [comment]
Since we have `transactions` and consider the `transaction` to be the `root_span` we need to store this information also on `transactions`.

**Comment by alvarolobato** [comment]
@watson is this still valid?

**Comment by watson** [comment]
@alvarolobato Yep

**Comment by jalvz** [comment]
So can we just implement this? Are all the agent devs aligned on field names, etc?

**Comment by watson** [comment]
I don't think this has been discussed or voted on yet. Since this issue was created we have published ECS, so we should probably also keep that in mind right?

ping @elastic/apm-agent-devs

**Comment by axw** [comment]
For naming, I'm wondering if we should call it "destination" rather than "peer", to fit with ECS. Would it ever make sense for the peer to be a source in a span context?

If we were to follow ECS at the intake level, then for the OT tags, how about this mapping:

 - peer.ipv4 -> destination.ip
 - peer.ipv6 -> destination.ip
 - peer.port -> destination.port
 - peer.hostname -> destination.domain

(I'm not super keen on the name "destination.domain", but I suppose it's a bit more accurate? Could be hostname, partial domain name, or an FQDN.)

I think `peer.service` would fit better as part of the span type/subtype.

**Comment by watson** [comment]
> For naming, I'm wondering if we should call it "destination" rather than "peer", to fit with ECS. Would it ever make sense for the peer to be a source in a span context?

I tried to answer that question in the issue description:

> Also I'm not sure I like the word peer, but I guess it's so that this can also contain information about an incoming request (something we currently reserve for transactions).

But as I said, I don't necessarily like the word peer either, but my understanding is that this is the reason behind it.

> peer.hostname -> destination.domain

As you also say, I don't like the word "domain" in this context either. Normally at least, we're trained to think of this as a hostname I guess. But it's probably going to be a domain in many cases.

**Comment by axw** [comment]
> I tried to answer that question in the issue description:
>
>> Also I'm not sure I like the word peer, but I guess it's so that this can also contain information about an incoming request (something we currently reserve for transactions).
>
> But as I said, I don't necessarily like the word peer either, but my understanding is that this is the reason behind it.

Understood; just echoing your sentiments, and seeing if we can come up with any alternatives.

I don't think we need to go 1:1 with OT tags, for a few reasons:

- for OT bridges, we have to explicitly map tags to context anyway
- ipv4/ipv6 distinction is unnecessary, and probably unhelpful to the server since it'll then need to add mutual exclusion to the schema
 - using "peer" only really makes sense if we want to align transaction and span context. IMO it's more helpful to call it "source" and "destination"; it's more immediately obvious what they mean, since their definitions are not dependent on context, unlike "peer"
 - again, "service" probably fits better in the span type; I'm not 100% sure on this one, need to see some more real-world OT data

**Comment by roncohen** [comment]
+1 on moving forward with `destination` for outgoing spans as a start. There are several areas where this will be interesting including SIEM and probably source maps.

**Comment by roncohen** [comment]
Closing in favor of https://github.com/elastic/apm/issues/115
