### ISSUE TITLE
Dependencies metrics regression after #7924

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/apm-server#8159]
## Description

Found while testing manually changes introduced for the new span fields `service.target.type` and `service.target.name` + compatibility back-fill.

The agent version does not seem to make any difference, both existing agents sending only `span.destination.service.resource` and newer agents also sending `span.service.target.*` are impacted.

It seems the Service Map layout is not impacted as it relies directly on `span.destination.service.resource`, it just can't properly display the dependencies chart.

## Steps to reproduce

- setup application with an agent
- use apm server on `main` branch at commit `e909e47ae` or later
- capture at least one transaction that calls a database
- observe that there are no service listed in dependencies
- doing the same with apm server at commit `aa7f0f1cd` or previous (just before this change was introduced)

**Comment by simitt** [comment]
@lahsivjar can you please look into this. Probably best to inspect the created events in ES to hopefully spot what is missing.

**Comment by lahsivjar** [comment]
In my case, as per the code [here](https://github.com/elastic/apm-agent-go/blob/dbce0fc5646cc428a8c4a1f3192a5bd5b071f7e5/module/apmsql/conn.go#L73), if `dsnInfo#Address` is empty then destination service is not populated. Based on the parsing logic for datasource info (dsnInfo) for sqlite in go-agent code ([ref](https://github.com/elastic/apm-agent-go/blob/dbce0fc5646cc428a8c4a1f3192a5bd5b071f7e5/module/apmsql/sqlite3/parser.go#L31-L33)), for in-memory database (denoted by `:memory:`), the `dsnInfo#Address` will always be empty causing the destination resource values to be missing and thus causing dependencies to be missing.

Based on above observation alone, it seems that the issue is not related to apm-server and might be an expected outcome. However, the issue observed originally might be different than what was observed by me so need inputs on a few points before proceeding:
1. Was an in-memory configuration used when the bug happened?
2. Was the same in-memory configuration used to test version prior to `aa7f0f1cd` commit ID?
3. Does the bug occur even when using databases like `postgres`, `mysql`?
