### ISSUE TITLE
Support the java agent team in making changes to the java agent attacher

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#8304]
@felixbarny & the java agent team will be driving the java agent attacher improvement work, described in https://github.com/elastic/apm-agent-java/issues/2649.

We need to ensure to provide apm-server and golang specific knowledge for supporting them.

**Comment by simitt** [comment]
@eyalkoren @felixbarny has the work on this started already? Some folks in the APM Server team have some PTO upcoming, let's ensure we sync in time for any kind of support that the java agent devs might need.

**Comment by eyalkoren** [comment]
I just started looking into this, but won't really get to that full-time before the week after next.
I think I have what I need in order to start, so nothing comes to mind for further sync atm.

**Comment by eyalkoren** [comment]
I opened #8590
It's only a draft because I want to get some initial feedback. In the mean time I am going to test it further (so far it is only tested as standalone and not through the APM Server).

It's probably full of bad Go practices, misconceptions etc., which is why it's be very useful to get an initial review ASAP.
Unit tests will be added of course, but I first want to test end to end.
Thanks!

**Comment by simitt** [comment]
Tracking task for docs https://github.com/elastic/apm-server/issues/8708

While testing the changes, we need to provide a matrix of (un-)supported operating systems as listed on the docs task.
