### ISSUE TITLE
Look into fuzzy testing for APM Server

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#842]
Look into existing frameworks and how we can improve our testsuite with using fuzzy testing. 
Starting point https://github.com/golang/go/issues/19109 and [go-fuzz](https://github.com/dvyukov/go-fuzz)

**Comment by axw** [comment]
Just saw this, after having done a bit of fuzzing of apm-agent-go recently. What I've done for the agent is not amazing, but it's a starting point:

- https://github.com/elastic/apm-agent-go/blob/master/gofuzz.go
- https://github.com/elastic/apm-agent-go/blob/master/model/gofuzz.go

The most interesting thing in those functions is that they use the apm-server/processor code to validate and decode the payloads. So this issue is already partially addressed at least.

**Comment by jalvz** [comment]
Another nice spacetime idea :) 
but I think we should close as we won't likely prioritize any time soon
