### ISSUE TITLE
Add Logs Intake API (POC)

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#8757]
The AWS lambda extension is already forwarding metrics and trace signals to the APM Server. Now the extension is adding support for collecting logs (https://github.com/elastic/apm-aws-lambda/issues/256). The APM server should be extended to also support proxying these logs to Elasticsearch. 

This issue can be used as meta issue and be further split up, if necessary. 

The POC should include:
* Extend the http server to support receiving logs events (provide a `logs` endpoint or add logs event support to existing event intake API).
* Add JSON spec for the logs format
* Parse & process log events
* Add a dedicated data stream, including mappings, ILM policy and ingest pipeline to the `apmpackage`. 
* Ship logs into one common `logs-apm.*` ES data stream for this POC.

## Expected outcome
* have a working prototype
* identify further work items and potential bottlenecks or issues.

## Out of Scope
* Define final data stream strategy. 
* Full end-to-end test coverage

**Comment by felixbarny** [comment]
> Add JSON spec for the logs format

I think we can keep the JSON spec very simple or maybe not even have a JSON spec. That's because there shouldn't be any required structure for logs and any top-level fields may be added.

The only field we may want to require is `@timestamp`, but in the context of LX, we're also thinking of ways to automatically set it to the ingest time if it's absent. For ECS JSON logs, which APM Agents will send we can, however, assume that there's always an `@timestamp` field.

When it comes to mappings, we need to take into account that ECS logs may add arbitrary key/value pairs to the root of the document. We could re-use some of the mappings I did for the Elasticsearch log ingestion API POC: https://github.com/elastic/elasticsearch/pull/88181/files#diff-0fba05a9236d9aa3866db886f0b6c24759be01a775023e1663b8f44f91951e62

The general idea is that only a handful of fields are indexed. Dynamic fields are added as runtime fields (`dynamic: runtime`).
