### ISSUE TITLE
Ensure APM Server makes full usage of available CPU resources

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#9182]
Previous benchmarks indicate that the APM Server performs better when scaling horizontally than vertically. This is a meta issue collecting steps necessary to ensure APM Server's throughput scales well when scaling the server's available CPU resources up. 

Previous investigations identified the modelindexer to be a bottle neck, and two action items were identified: 

- [x] https://github.com/elastic/apm-server/issues/9180
- [x] https://github.com/elastic/apm-server/issues/9181

The improvements need to be benchmarked; the goal is to provide full resource usage and (almost) linear scaling for APM Server's up to `32GB` of RAM (with aliquot CPU time) on ESS.

**Comment by kruskall** [comment]
I've reviewed the code in the linked PRs and looked at the trace files for specific benchmarks like `BenchmarkModelIndexer`.

I could not find any issues but I noticed the flush goroutine for the active indexers (introduced in https://github.com/elastic/apm-server/pull/9318) being always busy.
A goroutine being active might slow down GC and increase memory usage. I don't think that's going to be a big issue here due to the flush timer channel but I noticed some improvements and opened a PR to reduce the cpu time spent in the flush gorutine: https://github.com/elastic/apm-server/pull/9760
