### ISSUE TITLE
Record sample rate in trace event documents

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#9340]
It may be useful to know the sampling rate that was configured when an event was captured. For example, the APM storage explorer could use this to compare configured vs. effective sampling rate, and highlight changes to the sampling rate configuration in the timeline.

We already propagate this to APM Server, and use it for calculating transaction and service-destination metrics; we just don't record it in the event documents.

**Comment by sqren** [comment]
+1 for this. As mentioned in the issue description, this is useful in features like Storage Explorer. For the recent work on Mobile this is even more important, since features like Maps is purely based on sampled transactions. Without the sampling rate we won't be able to calculate metrics like throughput for a given region (country/city).

**Comment by axw** [comment]
It occurs to me now that this won't be enough for mobile, we'll also need them to send the sample rate to APM Server. Currently that's only done for agents that use intake-v2. I think that should be doable though.
