### ISSUE TITLE
Dropped transactions or errors can lead to user confusion

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#947]
A typical case is:

A user makes a bad deploy and as a result their app starts sending too many errors to the apm-server.
apm-server will saturate and return 503's for errors and also transactions.
User then will see a drop in transactions when the errors spike, and think that the errors are causing the transaction drop.
What happens actually is that the apm-server can't keep up and can't prioritize transactions over errors.

**Comment by alvarolobato** [comment]
The problem here is that you could lose many transactions if the errors spike, because errors would fill the queue and transactions would start to be discarded. This can lead you to draw non accurate conclusions from the data.

Having two queues could improve this situation but could also cause the two time of data to be out of sync in terms of time if one of the queues fall behind of the other. This can lead to more confusion to the user.

One possible solution could be trying to reduce the number of dropped transactions under heavy load, maybe by enabling overflow to disk in beats.

A possible way to improve the situation could be adding a indication in UI with the number of dropped transactions and errors.

We will timebox some time to investigate on a way to improve this situation and propose a way to improve it.

**Comment by jalvz** [comment]
> Having two queues could improve this situation but could also cause the two time of data to be out of sync in terms of time if one of the queues fall behind of the other

@alvarolobato what do you mean with that?

**Comment by alvarolobato** [comment]
@jalvz this was the summary of a discussion during a team meeting.
Basically if you have two queues and you start getting very different load you may start seeing up to date transactions but not getting the errors or the errors from an hour ago (or the opposite), because one of the queues is almost empty and the other one is not being able to keep up with the load.

This causes a bad user experience and may be miss-leading precisely in moments where you need to draw quick conclusions ie. a lot of errors coming from the monitored application.

**Comment by alvarolobato** [comment]
I don't know either my comment was a summary of the pros and cons discussed during the meeting.

**Comment by alvarolobato** [comment]
Putting back to the backlog and decide after all the changes to the V2 protocol and the refactor.

**Comment by simitt** [comment]
Moving this to backlog as I don't think we are blocked here atm, but rather postponed to work on this.

**Comment by graphaelli** [comment]
agreed
