### ISSUE TITLE
Update go-elasticsearch dependency when memory usage is fixed

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#9684]
Once https://github.com/elastic/go-elasticsearch/issues/557 is fixed, update the go-elasticsearch dependency in the APM Server.

**Comment by simitt** [comment]
Before updating, run some benchmarks to observe how memory and garbage collection behaves. Apparently GC load might be increased due to [copying of buffers](https://github.com/elastic/go-elasticsearch/blob/dc178adfaffbdb348a6ce421ee978192588449b2/esutil/bulk_indexer.go#L181).

**Comment by axw** [comment]
Bear in mind that we're not using go-elasticsearch's BulkIndexer in our code. We have our own optimised version. It's only the Profiling code that uses go-elasticsearch's version.

**Comment by christos68k** [comment]
To clarify, the Profiling [code](https://github.com/elastic/apm-server/blob/4d94aab988278ac946f1ff69580ec19824ac8bda/x-pack/apm-server/profiling/collector.go#L29) does not use go-elasticsearch directly, but is instead using the interface exposed through [apm-server/internal/elasticsearch](https://github.com/elastic/apm-server/blob/main/internal/elasticsearch/) which is a thin layer over [go-elasticsearch](https://github.com/elastic/apm-server/blob/4d94aab988278ac946f1ff69580ec19824ac8bda/internal/elasticsearch/bulk.go#L25).

I took another look just now and also noticed that another [indexer](https://github.com/elastic/apm-server/blob/main/internal/model/modelindexer/bulk_indexer.go) exists, which I'm assuming is what @axw refers to.

**Comment by simitt** [comment]
Good to know, so @christos68k there is also no urgency from the profiling perspective to update?

**Comment by christos68k** [comment]
There is urgency since anything that uses `apm-server/internal/elasticsearch` -which includes profiling- is practically using go-elasticsearch. 

However, there are other parts of apm-server that use a different [indexer](https://github.com/elastic/apm-server/blob/main/internal/model/modelindexer/bulk_indexer.go) as @axw mentioned. I looked at that briefly yesterday and it's a self-contained implementation that operates in a different manner (also allowing for requests limit). Maybe that's something that the profiling code could also reuse or move in a similar direction, but there is probably not enough time to do that before the next release (while updating the go-elasticsearch version seems possible).
