### ISSUE TITLE
[DOCS] Highlight APM Integration only supports Elasticsearch output

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/apm-server#9848]
As per December 2022, Elastic APM Integration only supports Elasticsearch output.
For clarity, this should be explicitly mentioned in the documentation - and not just listed in the limitations when [switching from APM Server to APM Integration](https://www.elastic.co/guide/en/apm/guide/current/upgrade-to-apm-integration.html#apm-integration-upgrade-limitations).

**Comment by simitt** [comment]
@bmorelli25 would be good to get your eyes on this.

**Comment by bmorelli25** [comment]
Hi @lucabelluccini. I'm struggling to think of where else we should mention this in the docs. Nothing in the APM documentation since ~8.0 mentions output options other than Elasticsearch. The only output documentation we have exists in the legacy topics, and all of that content has this warning at the top: `WARNING: This documentation refers to configuring the standalone (legacy) APM Server.`.

**Comment by bmorelli25** [comment]
I'm going to close this issue. This problem will be fixed indirectly in 8.8.
