### ISSUE TITLE
filter APM views on context.service.environment 

### ISSUE THREAD

**Issue by clarkgaybel** [elastic/apm-server#988]
**As** a User browsing APM views
**I want to** filter services by context.service.environment (staging, prod...)
**So that** I can see relevant data for one environment only.

(https://discuss.elastic.co/t/filter-service-by-environment/121573)

**Comment by jalvz** [comment]
Hi @clarkgaybel ,

This is a visualization feature request, so I am closing this issue here.  

You are more than welcome to reopen this issue in the Kibana repo and add an APM label to it so it gets to right people: https://github.com/elastic/kibana/issues/new?template=Feature_request.md

FYI what you are asking is WIP (https://github.com/elastic/kibana/pull/19469), and hopefully will be available in `6.4`.

Hope this helps!
